USE [DMS]
GO

/****** Object:  StoredProcedure [report].[BillingClientInvoiceDetailItem]    Script Date: 04/18/2016 11:14:23 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[report].[BillingClientInvoiceDetailItem]') AND type in (N'P', N'PC'))
DROP PROCEDURE [report].[BillingClientInvoiceDetailItem]
GO

USE [DMS]
GO

/****** Object:  StoredProcedure [report].[BillingClientInvoiceDetailItem]    Script Date: 04/18/2016 11:14:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [report].[BillingClientInvoiceDetailItem]
@pEntityID as int,
@pEntityKey as int
as

/***
exec Report.BillingClientInvoiceDetailItem 13, 35000 -- SR
exec Report.BillingClientInvoiceDetailItem 11, 110281 -- PO
exec Report.BillingClientInvoiceDetailItem 28, 282242 -- VI
exec Report.BillingClientInvoiceDetailItem 29, 12683 -- CL
exec Report.BillingClientInvoiceDetailItem 34, 100 -- MB
***/

declare	@EntityName as nvarchar(50),
		@EntityID as int

select	@EntityName = (select Name from dbo.Entity where ID = @pEntityID)


if object_id('tempdb..#tmpDetail', 'U') is not null drop table #tmpDetail

create table #tmpDetail
(
EntityID							int,
EntityKey							int,
EntityName							nvarchar(50),
ServiceRequestID					int,
ServiceRequestStatus				nvarchar(50),
ServiceRequestDatetime				datetime,
ServiceCode							nvarchar(255),
ClientID							int,
ClientName							nvarchar(50),
ProgramID							int,
ProgramName							nvarchar(50),
ProgramCode							nvarchar(20),
MemberID							int,
LastName							nvarchar(50),
FirstName							nvarchar(50),
MembershipNumber					nvarchar(25),
MemberSinceDate						datetime,
EffectiveDate						datetime,
ExpirationDate						datetime,
MemberCreateDate					date,
MemberCreateDatetime				datetime,
NumOfPOs							int,
PurchaseOrderID						int,
PurchaseOrderNumber					nvarchar(50),
PurchaseOrderDate					date,
PurchaseOrderDatetime				datetime,
PurchaseOrderStatus					nvarchar(50),
PurchaseOrderIsActive				bit,
ContactLastName						nvarchar(50),
ContactFirstName					nvarchar(50),
VIN									nvarchar(50),
VehicleYear							nvarchar(4),
VehicleMake							nvarchar(50),
VehicleModel						nvarchar(50),
VINModelYear						nvarchar(50),
VINModel							nvarchar(50),
VehicleCurrentMileage				int,
VehicleMileageUOM					nvarchar(50),
VehicleLicenseNumber				nvarchar(20),
VehicleLicenseState					nvarchar(2),
ServiceLocationAddress				nvarchar(100),
ServiceLocationCity					nvarchar(100),
ServiceLocationStateProvince		nvarchar(50),
DestinationDescription				nvarchar(100),
DestinationCity						nvarchar(100),
DestinationStateProvince			nvarchar(50),
TotalServiceAmount					money,
CoachNetServiceAmount				money,
MemberServiceAmount					money,
PurchaseOrderAmount					money,
ServiceRequestCCPaymentsReceived	money,
IsPaidByCompanyCC					int,
BillingApprovalCode					nvarchar(50),
IsCancelledSR						int,
IsDispatchIntended					int,
IsDispatched						int,
IsCancelledPO						int,
GOAReason							nvarchar(255),
IsVendorPay							int,
IsMemberPay							int,
IsReDispatch						int,
IsTechAssistance					int,
IsDiagnostics						int,
IsVerifyService						int,
IsISPSelection						int,
IsInfoContact						int,
IsNoMemberOnService					int,
IsMbrManuallyCreated				int,
IsImpoundRelease					int,
IsDirectTowApprovedDestination		int,
DispatchFee							money,
DispatchFeeBillToName				nvarchar(50),
VendorID							int,
VendorNumber						nvarchar(50),
VendorLocationID					int,
DealerNumber						nvarchar(50),
PrimaryVehicleDiagnosticCodeID		int,
PrimaryVehicleDiagnosticCodeName	nvarchar(100),
VehicleDiagnosticCodeCount			int,
InboundContactsTOTAL				int,
InboundContactsNEWCALL				int,
InboundContactsCUSTOMER				int,
InboundContactsVENDOR				int,
InboundContactsCLOSEDLOOP			int,
InboundContactsOTHER				int,
OutboundContactsTOTAL				int,
OutboundContactsNEWCALL				int,
OutboundContactsCUSTOMER			int,
OutboundContactsVENDOR				int,
OutboundContactsCLOSEDLOOP			int,
OutboundContactsOTHER				int,
DISPATCH							int,
NON_DISPATCH						int,
CUSTOMER_ASSISTANCE					int,
INFO								int,
OTHER								int,
PASS_THRU							int,
ServiceRequestComments				nvarchar(max),
ServiceRequestCommentsClaimNum		nvarchar(max),
ServiceRequestCommentsPACode		nvarchar(max),
ServiceRequestCommentsDealerID		nvarchar(max),
ClaimTypeName						nvarchar(50),
ClaimCategoryName					nvarchar(50),
ClaimStatus							nvarchar(50)
)


------------------------------------------------------------------------
-- Service Request Entity
------------------------------------------------------------------------
if @EntityName = 'ServiceRequest'
begin

	insert into #tmpDetail
	(EntityID,
	 EntityKey,
	 EntityName,
	 ServiceRequestID,
	 ServiceRequestStatus,
	 ServiceRequestDatetime,
	 ServiceCode,
	 ClientID,
	 ClientName,
	 ProgramID,
	 ProgramName,
	 ProgramCode,
	 MemberID,
	 LastName,
	 FirstName,
	 MembershipNumber,
 	 MemberSinceDate,
	 EffectiveDate,
	 ExpirationDate,
	 MemberCreateDate,
	 MemberCreateDatetime,
	 NumOfPOs,
	 PurchaseOrderID,
	 PurchaseOrderNumber,
	 PurchaseOrderDate,
	 PurchaseOrderDatetime,
	 PurchaseOrderStatus,
	 PurchaseOrderIsActive,
	 ContactLastName,
	 ContactFirstName,
	 VIN,
	 VehicleYear,
	 VehicleMake,
	 VehicleModel,
	 VINModelYear,
	 VINModel,
	 VehicleCurrentMileage,
	 VehicleMileageUOM,
	 VehicleLicenseNumber,
	 VehicleLicenseState,
	 ServiceLocationAddress,
	 ServiceLocationCity,
	 ServiceLocationStateProvince,
	 DestinationDescription,
	 DestinationCity,
	 DestinationStateProvince,
	 TotalServiceAmount,
	 CoachNetServiceAmount,
	 MemberServiceAmount,
	 PurchaseOrderAmount,
	 ServiceRequestCCPaymentsReceived,
	 IsPaidByCompanyCC,
	 BillingApprovalCode,
	 IsCancelledSR,
	 IsDispatchIntended,
	 IsDispatched,
	 IsCancelledPO,
	 GOAReason,
	 IsVendorPay,
	 IsMemberPay,
	 IsReDispatch,
	 IsTechAssistance,
	 IsDiagnostics,
	 IsVerifyService,
	 IsISPSelection,
	 IsInfoContact,
	 IsNoMemberOnService,
	 IsMbrManuallyCreated,
	 IsImpoundRelease,
	 IsDirectTowApprovedDestination,
	 DispatchFee,
	 DispatchFeeBillToName,
	 VendorID,
	 VendorNumber,
	 VendorLocationID,
	 DealerNumber,
	 PrimaryVehicleDiagnosticCodeID,
	 PrimaryVehicleDiagnosticCodeName,
	 VehicleDiagnosticCodeCount,
	 InboundContactsTOTAL,
	 InboundContactsNEWCALL,
	 InboundContactsCUSTOMER,
	 InboundContactsVENDOR,
	 InboundContactsCLOSEDLOOP,
	 InboundContactsOTHER,
	 OutboundContactsTOTAL,
	 OutboundContactsNEWCALL,
	 OutboundContactsCUSTOMER,
	 OutboundContactsVENDOR,
	 OutboundContactsCLOSEDLOOP,
	 OutboundContactsOTHER,
	 DISPATCH,
	 NON_DISPATCH,
	 CUSTOMER_ASSISTANCE,
	 INFO,
	 OTHER,
	 PASS_THRU,
	 ServiceRequestComments,
	 ServiceRequestCommentsClaimNum,
	 ServiceRequestCommentsPACode,
	 ServiceRequestCommentsDealerID,
	 ClaimTypeName,
	 ClaimCategoryName,
	 ClaimStatus)
	select	distinct
			@pEntityID, -- EntityID
			@pEntityKey,  -- EntityKey
			@EntityName,  -- EntityName
			ServiceRequestID,
			ServiceRequestStatus,
			ServiceRequestDatetime,
			ServiceCode,
			ClientID,
			ClientName,
			ProgramID,
			ProgramName,
			ProgramCode,
			MemberID,
			LastName,
			FirstName,
			MembershipNumber,
			MemberSinceDate,
			EffectiveDate,
			ExpirationDate,
			MemberCreateDate,
			MemberCreateDatetime,
			(select	count(*)
			 from	dbo.PurchaseOrder po with (nolock)
			 where	po.ServiceRequestID = srpo.ServiceRequestID) as NumOfPOs,
			null as PurchaseOrderID,
			null as PurchaseOrderNumber,
			null as PurchaseOrderDate,
			null as PurchaseOrderDatetime,
			null as PurchaseOrderStatus,
			null as PurchaseOrderIsActive,
			ContactLastName,
			ContactFirstName,
			VIN,
			VehicleYear,
			VehicleMake,
			VehicleModel,
			VINModelYear,
			VINModel,
			VehicleCurrentMileage,
			VehicleMileageUOM,
			VehicleLicenseNumber,
			VehicleLicenseState,
			ServiceLocationAddress,
			ServiceLocationCity,
			ServiceLocationStateProvince,
			DestinationDescription,
			DestinationCity,
			DestinationStateProvince,
			null as TotalServiceAmount,
			null as CoachNetServiceAmount,
			null as MemberServiceAmount,
			null as PurchaseOrderAmount,
			ServiceRequestCCPaymentsReceived,
			IsPaidByCompanyCC,
			BillingApprovalCode,
			IsCancelledSR,
			IsDispatchIntended,
			IsDispatched,
			IsCancelledPO,
			null GOAReason,
			IsVendorPay,
			IsMemberPay,
			IsReDispatch,
			IsTechAssistance,
			IsDiagnostics,
			IsVerifyService,
			IsISPSelection,
			IsInfoContact,
			IsNoMemberOnService,
			IsMbrManuallyCreated,
			IsImpoundRelease,
			IsDirectTowApprovedDestination,
			DispatchFee,
			DispatchFeeBillToName,
			VendorID,
			VendorNumber,
			VendorLocationID,
			DealerNumber,
			PrimaryVehicleDiagnosticCodeID,
			PrimaryVehicleDiagnosticCodeName,
			VehicleDiagnosticCodeCount,
			InboundContactsTOTAL,
			InboundContactsNEWCALL,
			InboundContactsCUSTOMER,
			InboundContactsVENDOR,
			InboundContactsCLOSEDLOOP,
			InboundContactsOTHER,
			OutboundContactsTOTAL,
			OutboundContactsNEWCALL,
			OutboundContactsCUSTOMER,
			OutboundContactsVENDOR,
			OutboundContactsCLOSEDLOOP,
			OutboundContactsOTHER,
			DISPATCH,
			NON_DISPATCH,
			CUSTOMER_ASSISTANCE,
			INFO,
			OTHER,
			PASS_THRU,
			ServiceRequestComments,
			ServiceRequestCommentsClaimNum,
			ServiceRequestCommentsPACode,
			ServiceRequestCommentsDealerID,
			null as ClaimTypeName,
			null as ClaimCategoryName,
			null as ClaimStatus
	from	dbo.vw_BillingServiceRequestsPurchaseOrders srpo
	where	1=1
	and		srpo.ServiceRequestID = @pEntityKey

end


------------------------------------------------------------------------
-- Purchase Order Entity
------------------------------------------------------------------------
if @EntityName = 'PurchaseOrder'
begin

	insert into #tmpDetail
	(EntityID,
	 EntityKey,
	 EntityName,
	 ServiceRequestID,
	 ServiceRequestStatus,
	 ServiceRequestDatetime,
	 ServiceCode,
	 ClientID,
	 ClientName,
	 ProgramID,
	 ProgramName,
	 ProgramCode,
	 MemberID,
	 LastName,
	 FirstName,
	 MembershipNumber,
 	 MemberSinceDate,
	 EffectiveDate,
	 ExpirationDate,
	 MemberCreateDate,
	 MemberCreateDatetime,
	 NumOfPOs,
	 PurchaseOrderID,
	 PurchaseOrderNumber,
	 PurchaseOrderDate,
	 PurchaseOrderDatetime,
	 PurchaseOrderStatus,
	 PurchaseOrderIsActive,
	 ContactLastName,
	 ContactFirstName,
	 VIN,
	 VehicleYear,
	 VehicleMake,
	 VehicleModel,
	 VINModelYear,
	 VINModel,
	 VehicleCurrentMileage,
	 VehicleMileageUOM,
	 VehicleLicenseNumber,
	 VehicleLicenseState,
	 ServiceLocationAddress,
	 ServiceLocationCity,
	 ServiceLocationStateProvince,
	 DestinationDescription,
	 DestinationCity,
	 DestinationStateProvince,
	 TotalServiceAmount,
	 CoachNetServiceAmount,
	 MemberServiceAmount,
	 PurchaseOrderAmount,
	 ServiceRequestCCPaymentsReceived,
	 IsPaidByCompanyCC,
	 BillingApprovalCode,
	 IsCancelledSR,
	 IsDispatchIntended,
	 IsDispatched,
	 IsCancelledPO,
	 GOAReason,
	 IsVendorPay,
	 IsMemberPay,
	 IsReDispatch,
	 IsTechAssistance,
	 IsDiagnostics,
	 IsVerifyService,
	 IsISPSelection,
	 IsInfoContact,
	 IsNoMemberOnService,
	 IsMbrManuallyCreated,
	 IsImpoundRelease,
	 IsDirectTowApprovedDestination,
	 DispatchFee,
	 DispatchFeeBillToName,
	 VendorID,
	 VendorNumber,
	 VendorLocationID,
	 DealerNumber,
	 PrimaryVehicleDiagnosticCodeID,
	 PrimaryVehicleDiagnosticCodeName,
	 VehicleDiagnosticCodeCount,
	 InboundContactsTOTAL,
	 InboundContactsNEWCALL,
	 InboundContactsCUSTOMER,
	 InboundContactsVENDOR,
	 InboundContactsCLOSEDLOOP,
	 InboundContactsOTHER,
	 OutboundContactsTOTAL,
	 OutboundContactsNEWCALL,
	 OutboundContactsCUSTOMER,
	 OutboundContactsVENDOR,
	 OutboundContactsCLOSEDLOOP,
	 OutboundContactsOTHER,
	 DISPATCH,
	 NON_DISPATCH,
	 CUSTOMER_ASSISTANCE,
	 INFO,
	 OTHER,
	 PASS_THRU,
	 ServiceRequestComments,
	 ServiceRequestCommentsClaimNum,
	 ServiceRequestCommentsPACode,
	 ServiceRequestCommentsDealerID,
	 ClaimTypeName,
	 ClaimCategoryName,
	 ClaimStatus)
	select	distinct
			@pEntityID as EntityID,
			@pEntityKey as EntityKey,
			@EntityName as EntityName,
			ServiceRequestID,
			ServiceRequestStatus,
			ServiceRequestDatetime,
			ServiceCode,
			ClientID,
			ClientName,
			ProgramID,
			ProgramName,
			ProgramCode,
			MemberID,
			LastName,
			FirstName,
			MembershipNumber,
			MemberSinceDate,
			EffectiveDate,
			ExpirationDate,
			MemberCreateDate,
			MemberCreateDatetime,
			null as NumOfPOs,
			PurchaseOrderID,
			PurchaseOrderNumber,
			PurchaseOrderDate,
			PurchaseOrderDatetime,
			PurchaseOrderStatus,
			PurchaseOrderIsActive,
			ContactLastName,
			ContactFirstName,
			VIN,
			VehicleYear,
			VehicleMake,
			VehicleModel,
			VINModelYear,
			VINModel,
			VehicleCurrentMileage,
			VehicleMileageUOM,
			VehicleLicenseNumber,
			VehicleLicenseState,
			ServiceLocationAddress,
			ServiceLocationCity,
			ServiceLocationStateProvince,
			DestinationDescription,
			DestinationCity,
			DestinationStateProvince,
			TotalServiceAmount,
			CoachNetServiceAmount,
			MemberServiceAmount,
			PurchaseOrderAmount,
			ServiceRequestCCPaymentsReceived,
			IsPaidByCompanyCC,
			BillingApprovalCode,
			IsCancelledSR,
			IsDispatchIntended,
			IsDispatched,
			IsCancelledPO,
			null GOAReason,
			IsVendorPay,
			IsMemberPay,
			IsReDispatch,
			IsTechAssistance,
			IsDiagnostics,
			IsVerifyService,
			IsISPSelection,
			IsInfoContact,
			IsNoMemberOnService,
			IsMbrManuallyCreated,
			IsImpoundRelease,
			IsDirectTowApprovedDestination,
			DispatchFee,
			DispatchFeeBillToName,
			VendorID,
			VendorNumber,
			VendorLocationID,
			DealerNumber,
			PrimaryVehicleDiagnosticCodeID,
			PrimaryVehicleDiagnosticCodeName,
			VehicleDiagnosticCodeCount,
			InboundContactsTOTAL,
			InboundContactsNEWCALL,
			InboundContactsCUSTOMER,
			InboundContactsVENDOR,
			InboundContactsCLOSEDLOOP,
			InboundContactsOTHER,
			OutboundContactsTOTAL,
			OutboundContactsNEWCALL,
			OutboundContactsCUSTOMER,
			OutboundContactsVENDOR,
			OutboundContactsCLOSEDLOOP,
			OutboundContactsOTHER,
			DISPATCH,
			NON_DISPATCH,
			CUSTOMER_ASSISTANCE,
			INFO,
			OTHER,
			PASS_THRU,
			ServiceRequestComments,
			ServiceRequestCommentsClaimNum,
			ServiceRequestCommentsPACode,
			ServiceRequestCommentsDealerID,
			null as ClaimTypeName,
			null as ClaimCategoryName,
			null as ClaimStatus
	from	dbo.vw_BillingServiceRequestsPurchaseOrders srpo
	where	1=1
	and		srpo.PurchaseOrderID = @pEntityKey

end

------------------------------------------------------------------------
-- Vendor Invoice Entity
------------------------------------------------------------------------
if @EntityName = 'VendorInvoice'
begin

	insert into #tmpDetail
	(EntityID,
	 EntityKey,
	 EntityName,
	 ServiceRequestID,
	 ServiceRequestStatus,
	 ServiceRequestDatetime,
	 ServiceCode,
	 ClientID,
	 ClientName,
	 ProgramID,
	 ProgramName,
	 ProgramCode,
	 MemberID,
	 LastName,
	 FirstName,
	 MembershipNumber,
 	 MemberSinceDate,
	 EffectiveDate,
	 ExpirationDate,
	 MemberCreateDate,
	 MemberCreateDatetime,
	 NumOfPOs,
	 PurchaseOrderID,
	 PurchaseOrderNumber,
	 PurchaseOrderDate,
	 PurchaseOrderDatetime,
	 PurchaseOrderStatus,
	 PurchaseOrderIsActive,
	 ContactLastName,
	 ContactFirstName,
	 VIN,
	 VehicleYear,
	 VehicleMake,
	 VehicleModel,
	 VINModelYear,
	 VINModel,
	 VehicleCurrentMileage,
	 VehicleMileageUOM,
	 VehicleLicenseNumber,
	 VehicleLicenseState,
	 ServiceLocationAddress,
	 ServiceLocationCity,
	 ServiceLocationStateProvince,
	 DestinationDescription,
	 DestinationCity,
	 DestinationStateProvince,
	 TotalServiceAmount,
	 CoachNetServiceAmount,
	 MemberServiceAmount,
	 PurchaseOrderAmount,
	 ServiceRequestCCPaymentsReceived,
	 IsPaidByCompanyCC,
	 BillingApprovalCode,
	 IsCancelledSR,
	 IsDispatchIntended,
	 IsDispatched,
	 IsCancelledPO,
	 GOAReason,
	 IsVendorPay,
	 IsMemberPay,
	 IsReDispatch,
	 IsTechAssistance,
	 IsDiagnostics,
	 IsVerifyService,
	 IsISPSelection,
	 IsInfoContact,
	 IsNoMemberOnService,
	 IsMbrManuallyCreated,
	 IsImpoundRelease,
	 IsDirectTowApprovedDestination,
	 DispatchFee,
	 DispatchFeeBillToName,
	 VendorID,
	 VendorNumber,
	 VendorLocationID,
	 DealerNumber,
	 PrimaryVehicleDiagnosticCodeID,
	 PrimaryVehicleDiagnosticCodeName,
	 VehicleDiagnosticCodeCount,
	 InboundContactsTOTAL,
	 InboundContactsNEWCALL,
	 InboundContactsCUSTOMER,
	 InboundContactsVENDOR,
	 InboundContactsCLOSEDLOOP,
	 InboundContactsOTHER,
	 OutboundContactsTOTAL,
	 OutboundContactsNEWCALL,
	 OutboundContactsCUSTOMER,
	 OutboundContactsVENDOR,
	 OutboundContactsCLOSEDLOOP,
	 OutboundContactsOTHER,
	 DISPATCH,
	 NON_DISPATCH,
	 CUSTOMER_ASSISTANCE,
	 INFO,
	 OTHER,
	 PASS_THRU,
	 ServiceRequestComments,
	 ServiceRequestCommentsClaimNum,
	 ServiceRequestCommentsPACode,
	 ServiceRequestCommentsDealerID,
	 ClaimTypeName,
	 ClaimCategoryName,
	 ClaimStatus)
	select	distinct
			@pEntityID as EntityID,
			@pEntityKey as EntityKey,
			@EntityName as EntityName,
			srpo.ServiceRequestID,
			srpo.ServiceRequestStatus,
			srpo.ServiceRequestDatetime,
			srpo.ServiceCode,
			srpo.ClientID,
			srpo.ClientName,
			srpo.ProgramID,
			srpo.ProgramName,
			srpo.ProgramCode,
			vi.MemberID,
			vi.LastName,
			vi.FirstName,
			vi.MembershipNumber,
			vi.MemberSinceDate,
			vi.EffectiveDate,
			vi.ExpirationDate,
			vi.MemberCreateDate,
			vi.MemberCreateDatetime,
			(select	count(*)
			 from	dbo.PurchaseOrder po with (nolock)
			 where	po.ServiceRequestID = srpo.ServiceRequestID) as NumOfPOs,
			srpo.PurchaseOrderID,
			srpo.PurchaseOrderNumber,
			srpo.PurchaseOrderDate,
			srpo.PurchaseOrderDatetime,
			srpo.PurchaseOrderStatus,
			srpo.PurchaseOrderIsActive,
			srpo.ContactLastName,
			srpo.ContactFirstName,
			vi.VIN,
			vi.VehicleYear,
			vi.VehicleMake,
			vi.VehicleModel,
			vi.VINModelYear,
			vi.VINModel,
			vi.VehicleCurrentMileage,
			vi.VehicleMileageUOM,
			vi.VehicleLicenseNumber,
			vi.VehicleLicenseState,
			srpo.ServiceLocationAddress,
			srpo.ServiceLocationCity,
			srpo.ServiceLocationStateProvince,
			srpo.DestinationDescription,
			srpo.DestinationCity,
			srpo.DestinationStateProvince,
			srpo.TotalServiceAmount,
			CoachNetServiceAmount,
			srpo.MemberServiceAmount,
			srpo.PurchaseOrderAmount,
			srpo.ServiceRequestCCPaymentsReceived,
			srpo.IsPaidByCompanyCC,
			srpo.BillingApprovalCode,
			srpo.IsCancelledSR,
			srpo.IsDispatchIntended,
			srpo.IsDispatched,
			srpo.IsCancelledPO,
			srpo.GOAReason,
			srpo.IsVendorPay,
			srpo.IsMemberPay,
			srpo.IsReDispatch,
			srpo.IsTechAssistance,
			srpo.IsDiagnostics,
			srpo.IsVerifyService,
			srpo.IsISPSelection,
			srpo.IsInfoContact,
			srpo.IsNoMemberOnService,
			srpo.IsMbrManuallyCreated,
			srpo.IsImpoundRelease,
			srpo.IsDirectTowApprovedDestination,
			srpo.DispatchFee,
			srpo.DispatchFeeBillToName,
			srpo.VendorID,
			srpo.VendorNumber,
			srpo.VendorLocationID,
			srpo.DealerNumber,
			srpo.PrimaryVehicleDiagnosticCodeID,
			srpo.PrimaryVehicleDiagnosticCodeName,
			srpo.VehicleDiagnosticCodeCount,
			srpo.InboundContactsTOTAL,
			srpo.InboundContactsNEWCALL,
			srpo.InboundContactsCUSTOMER,
			srpo.InboundContactsVENDOR,
			srpo.InboundContactsCLOSEDLOOP,
			srpo.InboundContactsOTHER,
			srpo.OutboundContactsTOTAL,
			srpo.OutboundContactsNEWCALL,
			srpo.OutboundContactsCUSTOMER,
			srpo.OutboundContactsVENDOR,
			srpo.OutboundContactsCLOSEDLOOP,
			srpo.OutboundContactsOTHER,
			srpo.DISPATCH,
			srpo.NON_DISPATCH,
			srpo.CUSTOMER_ASSISTANCE,
			srpo.INFO,
			srpo.OTHER,
			srpo.PASS_THRU,
			srpo.ServiceRequestComments,
			srpo.ServiceRequestCommentsClaimNum,
			srpo.ServiceRequestCommentsPACode,
			srpo.ServiceRequestCommentsDealerID,
			null as ClaimTypeName,
			null as ClaimCategoryName,
			null as ClaimStatus
	from	dbo.vw_BillingVendorInvoices vi
	left outer join	dbo.vw_BillingServiceRequestsPurchaseOrders srpo on srpo.EntityKey_PurchaseOrder = vi.PurchaseOrderID
	where	1=1
	and		vi.VendorInvoiceID = @pEntityKey

end


------------------------------------------------------------------------
-- Claim Entity
------------------------------------------------------------------------
if @EntityName = 'Claim'
begin

	insert into #tmpDetail
	(EntityID,
	 EntityKey,
	 EntityName,
	 ServiceRequestID,
	 ServiceRequestStatus,
	 ServiceRequestDatetime,
	 ServiceCode,
	 ClientID,
	 ClientName,
	 ProgramID,
	 ProgramName,
	 ProgramCode,
	 MemberID,
	 LastName,
	 FirstName,
	 MembershipNumber,
 	 MemberSinceDate,
	 EffectiveDate,
	 ExpirationDate,
	 MemberCreateDate,
	 MemberCreateDatetime,
	 NumOfPOs,
	 PurchaseOrderID,
	 PurchaseOrderNumber,
	 PurchaseOrderDate,
	 PurchaseOrderDatetime,
	 PurchaseOrderStatus,
	 PurchaseOrderIsActive,
	 ContactLastName,
	 ContactFirstName,
	 VIN,
	 VehicleYear,
	 VehicleMake,
	 VehicleModel,
	 VINModelYear,
	 VINModel,
	 VehicleCurrentMileage,
	 VehicleMileageUOM,
	 VehicleLicenseNumber,
	 VehicleLicenseState,
	 ServiceLocationAddress,
	 ServiceLocationCity,
	 ServiceLocationStateProvince,
	 DestinationDescription,
	 DestinationCity,
	 DestinationStateProvince,
	 TotalServiceAmount,
	 CoachNetServiceAmount,
	 MemberServiceAmount,
	 PurchaseOrderAmount,
	 ServiceRequestCCPaymentsReceived,
	 IsPaidByCompanyCC,
	 BillingApprovalCode,
	 IsCancelledSR,
	 IsDispatchIntended,
	 IsDispatched,
	 IsCancelledPO,
	 GOAReason,
	 IsVendorPay,
	 IsMemberPay,
	 IsReDispatch,
	 IsTechAssistance,
	 IsDiagnostics,
	 IsVerifyService,
	 IsISPSelection,
	 IsInfoContact,
	 IsNoMemberOnService,
	 IsMbrManuallyCreated,
	 IsImpoundRelease,
	 IsDirectTowApprovedDestination,
	 DispatchFee,
	 DispatchFeeBillToName,
	 VendorID,
	 VendorNumber,
	 VendorLocationID,
	 DealerNumber,
	 PrimaryVehicleDiagnosticCodeID,
	 PrimaryVehicleDiagnosticCodeName,
	 VehicleDiagnosticCodeCount,
	 InboundContactsTOTAL,
	 InboundContactsNEWCALL,
	 InboundContactsCUSTOMER,
	 InboundContactsVENDOR,
	 InboundContactsCLOSEDLOOP,
	 InboundContactsOTHER,
	 OutboundContactsTOTAL,
	 OutboundContactsNEWCALL,
	 OutboundContactsCUSTOMER,
	 OutboundContactsVENDOR,
	 OutboundContactsCLOSEDLOOP,
	 OutboundContactsOTHER,
	 DISPATCH,
	 NON_DISPATCH,
	 CUSTOMER_ASSISTANCE,
	 INFO,
	 OTHER,
	 PASS_THRU,
	 ServiceRequestComments,
	 ServiceRequestCommentsClaimNum,
	 ServiceRequestCommentsPACode,
	 ServiceRequestCommentsDealerID,
	 ClaimTypeName,
	 ClaimCategoryName,
	 ClaimStatus)
	select	distinct
			@pEntityID as EntityID,
			@pEntityKey as EntityKey,
			@EntityName as EntityName,
			null as ServiceRequestID,
			null as ServiceRequestStatus,
			null as ServiceRequestDatetime,
			null as ServiceCode,
			cl.ClientID,
			cl.ClientName,
			cl.ProgramID,
			cl.ProgramName,
			cl.ProgramCode,
			cl.MemberID,
			cl.LastName,
			cl.FirstName,
			cl.MembershipNumber,
			cl.MemberSinceDate,
			cl.EffectiveDate,
			cl.ExpirationDate,
			cl.MemberCreateDate,
			cl.MemberCreateDatetime,
			(select	count(*)
			 from	dbo.PurchaseOrder po with (nolock)
			 where	po.ServiceRequestID = srpo.ServiceRequestID) as NumOfPOs,
			cl.PurchaseOrderID,
			null as PurchaseOrderNumber,
			null as PurchaseOrderDate,
			null as PurchaseOrderDatetime,
			null as PurchaseOrderStatus,
			null as PurchaseOrderIsActive,
			cl.ContactName,
			null ContactFirstName,
			cl.VIN,
			cl.VehicleYear,
			cl.VehicleMake,
			cl.VehicleModel,
			cl.VINModelYear,
			cl.VINModel,
			cl.VehicleCurrentMileage,
			cl.VehicleMileageUOM,
			cl.VehicleLicenseNumber,
			cl.VehicleLicenseState,
			null as ServiceLocationAddress,
			null as ServiceLocationCity,
			null as ServiceLocationStateProvince,
			null as DestinationDescription,
			null as DestinationCity,
			null as DestinationStateProvince,
			null as TotalServiceAmount,
			null as CoachNetServiceAmount,
			null as MemberServiceAmount,
			null as PurchaseOrderAmount,
			null as ServiceRequestCCPaymentsReceived,
			null as IsPaidByCompanyCC,
			null as BillingApprovalCode,
			null as IsCancelledSR,
			null as IsDispatchIntended,
			null as IsDispatched,
			null as IsCancelledPO,
			null as GOAReason,
			null as IsVendorPay,
			null as IsMemberPay,
			null as IsReDispatch,
			null as IsTechAssistance,
			null as IsDiagnostics,
			null as IsVerifyService,
			null as IsISPSelection,
			null as IsInfoContact,
			null as IsNoMemberOnService,
			null as IsMbrManuallyCreated,
			null as IsImpoundRelease,
			null as IsDirectTowApprovedDestination,
			null as DispatchFee,
			null as DispatchFeeBillToName,
			cl.VendorID,
			cl.VendorNumber,
			null VendorLocationID,
			null as DealerNumber,
			null as PrimaryVehicleDiagnosticCodeID,
			null as PrimaryVehicleDiagnosticCodeName,
			null as VehicleDiagnosticCodeCount,
			null as InboundContactsTOTAL,
			null as InboundContactsNEWCALL,
			null as InboundContactsCUSTOMER,
			null as InboundContactsVENDOR,
			null as InboundContactsCLOSEDLOOP,
			null as InboundContactsOTHER,
			null as OutboundContactsTOTAL,
			null as OutboundContactsNEWCALL,
			null as OutboundContactsCUSTOMER,
			null as OutboundContactsVENDOR,
			null as OutboundContactsCLOSEDLOOP,
			null as OutboundContactsOTHER,
			null as DISPATCH,
			null as NON_DISPATCH,
			null as CUSTOMER_ASSISTANCE,
			null as INFO,
			null as OTHER,
			null as PASS_THRU,
			null as ServiceRequestComments,
			null as ServiceRequestCommentsClaimNum,
			null as ServiceRequestCommentsPACode,
			null as ServiceRequestCommentsDealerID,
			cl.ClaimTypeName,
			cl.ClaimCategoryName,
			cl.ClaimStatus
	from	dbo.vw_BillingClaims cl
	left outer join	dbo.vw_BillingServiceRequestsPurchaseOrders srpo on srpo.EntityKey_PurchaseOrder = cl.PurchaseOrderID
	where	1=1
	and		cl.ClaimID = @pEntityKey

end


------------------------------------------------------------------------
-- MemberCount Entity
------------------------------------------------------------------------
if @EntityName = 'MemberCounts'
begin

	insert into #tmpDetail
	(EntityID,
	 EntityKey,
	 EntityName,
	 ServiceRequestID,
	 ServiceRequestStatus,
	 ServiceRequestDatetime,
	 ServiceCode,
	 ClientID,
	 ClientName,
	 ProgramID,
	 ProgramName,
	 ProgramCode,
	 MemberID,
	 LastName,
	 FirstName,
	 MembershipNumber,
 	 MemberSinceDate,
	 EffectiveDate,
	 ExpirationDate,
	 MemberCreateDate,
	 MemberCreateDatetime,
	 NumOfPOs,
	 PurchaseOrderID,
	 PurchaseOrderNumber,
	 PurchaseOrderDate,
	 PurchaseOrderDatetime,
	 PurchaseOrderStatus,
	 PurchaseOrderIsActive,
	 ContactLastName,
	 ContactFirstName,
	 VIN,
	 VehicleYear,
	 VehicleMake,
	 VehicleModel,
	 VINModelYear,
	 VINModel,
	 VehicleCurrentMileage,
	 VehicleMileageUOM,
	 VehicleLicenseNumber,
	 VehicleLicenseState,
	 ServiceLocationAddress,
	 ServiceLocationCity,
	 ServiceLocationStateProvince,
	 DestinationDescription,
	 DestinationCity,
	 DestinationStateProvince,
	 TotalServiceAmount,
	 CoachNetServiceAmount,
	 MemberServiceAmount,
	 PurchaseOrderAmount,
	 ServiceRequestCCPaymentsReceived,
	 IsPaidByCompanyCC,
	 BillingApprovalCode,
	 IsCancelledSR,
	 IsDispatchIntended,
	 IsDispatched,
	 IsCancelledPO,
	 GOAReason,
	 IsVendorPay,
	 IsMemberPay,
	 IsReDispatch,
	 IsTechAssistance,
	 IsDiagnostics,
	 IsVerifyService,
	 IsISPSelection,
	 IsInfoContact,
	 IsNoMemberOnService,
	 IsMbrManuallyCreated,
	 IsImpoundRelease,
	 IsDirectTowApprovedDestination,
	 DispatchFee,
	 DispatchFeeBillToName,
	 VendorID,
	 VendorNumber,
	 VendorLocationID,
	 DealerNumber,
	 PrimaryVehicleDiagnosticCodeID,
	 PrimaryVehicleDiagnosticCodeName,
	 VehicleDiagnosticCodeCount,
	 InboundContactsTOTAL,
	 InboundContactsNEWCALL,
	 InboundContactsCUSTOMER,
	 InboundContactsVENDOR,
	 InboundContactsCLOSEDLOOP,
	 InboundContactsOTHER,
	 OutboundContactsTOTAL,
	 OutboundContactsNEWCALL,
	 OutboundContactsCUSTOMER,
	 OutboundContactsVENDOR,
	 OutboundContactsCLOSEDLOOP,
	 OutboundContactsOTHER,
	 DISPATCH,
	 NON_DISPATCH,
	 CUSTOMER_ASSISTANCE,
	 INFO,
	 OTHER,
	 PASS_THRU,
	 ServiceRequestComments,
	 ServiceRequestCommentsClaimNum,
	 ServiceRequestCommentsPACode,
	 ServiceRequestCommentsDealerID,
	 ClaimTypeName,
	 ClaimCategoryName,
	 ClaimStatus)
	select	distinct
			@pEntityID as EntityID,
			@pEntityKey as EntityKey,
			@EntityName as EntityName,
			null as ServiceRequestID,
			null as ServiceRequestStatus,
			null as ServiceRequestDatetime,
			null as ServiceCode,
			bm.ClientID,
			bm.ClientName,
			bm.ProgramID,
			bm.ProgramName,
			bm.ProgramCode,
			bm.MemberID,
			bm.LastName,
			bm.FirstName,
			bm.MembershipNumber,
			bm.MemberSinceDate,
			bm.EffectiveDate,
			bm.ExpirationDate,
			bm.DMSMemberCreateDate,
			bm.DMSMemberCreateDatetime,
			null as NumOfPOs,
			null as PurchaseOrderID,
			null as PurchaseOrderNumber,
			null as PurchaseOrderDate,
			null as PurchaseOrderDatetime,
			null as PurchaseOrderStatus,
			null as PurchaseOrderIsActive,
			null as ContactName,
			null ContactFirstName,
			bm.VIN,
			null as VehicleYear,
			null as VehicleMake,
			dbo.fnc_BillingVINModel(bm.VIN) as VehicleModel,
			bm.VINModelYear,
			null as VINModel,
			null as VehicleCurrentMileage,
			null as VehicleMileageUOM,
			null as VehicleLicenseNumber,
			null as VehicleLicenseState,
			null as ServiceLocationAddress,
			null as ServiceLocationCity,
			null as ServiceLocationStateProvince,
			null as DestinationDescription,
			null as DestinationCity,
			null as DestinationStateProvince,
			null as TotalServiceAmount,
			null as CoachNetServiceAmount,
			null as MemberServiceAmount,
			null as PurchaseOrderAmount,
			null as ServiceRequestCCPaymentsReceived,
			null as IsPaidByCompanyCC,
			null as BillingApprovalCode,
			null as IsCancelledSR,
			null as IsDispatchIntended,
			null as IsDispatched,
			null as IsCancelledPO,
			null as GOAReason,
			null as IsVendorPay,
			null as IsMemberPay,
			null as IsReDispatch,
			null as IsTechAssistance,
			null as IsDiagnostics,
			null as IsVerifyService,
			null as IsISPSelection,
			null as IsInfoContact,
			null as IsNoMemberOnService,
			null as IsMbrManuallyCreated,
			null as IsImpoundRelease,
			null as IsDirectTowApprovedDestination,
			null as DispatchFee,
			null as DispatchFeeBillToName,
			null as VendorID,
			null as VendorNumber,
			null VendorLocationID,
			null as DealerNumber,
			null as PrimaryVehicleDiagnosticCodeID,
			null as PrimaryVehicleDiagnosticCodeName,
			null as VehicleDiagnosticCodeCount,
			null as InboundContactsTOTAL,
			null as InboundContactsNEWCALL,
			null as InboundContactsCUSTOMER,
			null as InboundContactsVENDOR,
			null as InboundContactsCLOSEDLOOP,
			null as InboundContactsOTHER,
			null as OutboundContactsTOTAL,
			null as OutboundContactsNEWCALL,
			null as OutboundContactsCUSTOMER,
			null as OutboundContactsVENDOR,
			null as OutboundContactsCLOSEDLOOP,
			null as OutboundContactsOTHER,
			null as DISPATCH,
			null as NON_DISPATCH,
			null as CUSTOMER_ASSISTANCE,
			null as INFO,
			null as OTHER,
			null as PASS_THRU,
			null as ServiceRequestComments,
			null as ServiceRequestCommentsClaimNum,
			null as ServiceRequestCommentsPACode,
			null as ServiceRequestCommentsDealerID,
			null as ClaimTypeName,
			null as ClaimCategoryName,
			null as ClaimStatus
	from	dbo.vw_BillingMembers bm
	where	1=1
	and		bm.DMSMemberCountsID = @pEntityKey

end



------------------------------------------------------------------------
-- Return Data
------------------------------------------------------------------------
select	EntityID,
		EntityKey,
		EntityName,
		ServiceRequestID,
		ServiceRequestStatus,
		ServiceRequestDatetime,
		ServiceCode,
		ClientID,
		ClientName,
		ProgramID,
		ProgramName,
		ProgramCode,
		MemberID,
		LastName,
		FirstName,
		MembershipNumber,
		MemberSinceDate,
		EffectiveDate,
		ExpirationDate,
		MemberCreateDate,
		MemberCreateDatetime,
		NumOfPOs,
		PurchaseOrderID,
		PurchaseOrderNumber,
		PurchaseOrderDate,
		PurchaseOrderDatetime,
		PurchaseOrderStatus,
		PurchaseOrderIsActive,
		ContactLastName,
		ContactFirstName,
		VIN,
		VehicleYear,
		VehicleMake,
		VehicleModel,
		VINModelYear,
		VINModel,
		VehicleCurrentMileage,
		VehicleMileageUOM,
		VehicleLicenseNumber,
		VehicleLicenseState,
		ServiceLocationAddress,
		ServiceLocationCity,
		ServiceLocationStateProvince,
		DestinationDescription,
		DestinationCity,
		DestinationStateProvince,
		TotalServiceAmount,
		CoachNetServiceAmount,
		MemberServiceAmount,
		PurchaseOrderAmount,
		ServiceRequestCCPaymentsReceived,
		IsPaidByCompanyCC,
		BillingApprovalCode,
		IsCancelledSR,
		IsDispatchIntended,
		IsDispatched,
		IsCancelledPO,
		GOAReason,
		IsVendorPay,
		IsMemberPay,
		IsReDispatch,
		IsTechAssistance,
		IsDiagnostics,
		IsVerifyService,
		IsISPSelection,
		IsInfoContact,
		IsNoMemberOnService,
		IsMbrManuallyCreated,
		IsImpoundRelease,
		IsDirectTowApprovedDestination,
		DispatchFee,
		DispatchFeeBillToName,
		VendorID,
		VendorNumber,
		VendorLocationID,
		DealerNumber,
		PrimaryVehicleDiagnosticCodeID,
		PrimaryVehicleDiagnosticCodeName,
		VehicleDiagnosticCodeCount,
		InboundContactsTOTAL,
		InboundContactsNEWCALL,
		InboundContactsCUSTOMER,
		InboundContactsVENDOR,
		InboundContactsCLOSEDLOOP,
		InboundContactsOTHER,
		OutboundContactsTOTAL,
		OutboundContactsNEWCALL,
		OutboundContactsCUSTOMER,
		OutboundContactsVENDOR,
		OutboundContactsCLOSEDLOOP,
		OutboundContactsOTHER,
		DISPATCH,
		NON_DISPATCH,
		CUSTOMER_ASSISTANCE,
		INFO,
		OTHER,
		PASS_THRU,
		ServiceRequestComments,
		ServiceRequestCommentsClaimNum,
		ServiceRequestCommentsPACode,
		ServiceRequestCommentsDealerID,
		ClaimTypeName,
		ClaimCategoryName,
		ClaimStatus
from	#tmpDetail


GO

