//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberAPI.DAL
{
    using System;
    
    public partial class GetMemberResult
    {
        public int ID { get; set; }
        public string MemberNumber { get; set; }
        public int IsPrimary { get; set; }
        public Nullable<int> PlanID { get; set; }
        public string PlanName { get; set; }
        public string ProductCode { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public System.DateTime BirthDay { get; set; }
        public Nullable<int> HomeAddressID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string StateProvince { get; set; }
        public string PostalCode { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> HomePhoneID { get; set; }
        public string HomePhoneTypeCode { get; set; }
        public string HomePhoneCountryCode { get; set; }
        public string HomePhoneAreaCode { get; set; }
        public string HomePhone { get; set; }
        public Nullable<int> CellPhoneID { get; set; }
        public string CellPhoneTypeCode { get; set; }
        public string CellPhoneCountryCode { get; set; }
        public string CellPhoneAreaCode { get; set; }
        public string CellPhone { get; set; }
        public string Email1 { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> MemberSinceDate { get; set; }
        public bool MailExclude { get; set; }
        public bool FaxExclude { get; set; }
        public bool EmailExclude { get; set; }
        public bool DirExclude { get; set; }
        public bool NMCInvoiceExclude { get; set; }
        public bool NMCPhoneExclude { get; set; }
    }
}
