//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberAPI.DAL
{
    using System;
    
    public partial class LoginResult
    {
        public Nullable<int> PersonID { get; set; }
        public string NMCMemberNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> PlanID { get; set; }
        public string PlanName { get; set; }
        public Nullable<System.DateTime> MemberSinceDate { get; set; }
        public Nullable<System.DateTime> CurrentSubscriptionStartDate { get; set; }
        public Nullable<System.DateTime> CurrentSubscriptionExpirationDate { get; set; }
        public string MemberNumber { get; set; }
        public string ProductCode { get; set; }
        public int IsActive { get; set; }
        public Nullable<int> MasterPersonID { get; set; }
        public string MasterMemberNumber { get; set; }
        public string MembershipNumber { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public int MasterMember { get; set; }
    }
}
