//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberAPI.Services.Aptify {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesRep", Namespace="http://schemas.datacontract.org/2004/07/CNET.BusinessService")]
    [System.SerializableAttribute()]
    public partial class SalesRep : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DealershipIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneAreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DealershipID {
            get {
                return this.DealershipIDField;
            }
            set {
                if ((this.DealershipIDField.Equals(value) != true)) {
                    this.DealershipIDField = value;
                    this.RaisePropertyChanged("DealershipID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneAreaCode {
            get {
                return this.PhoneAreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneAreaCodeField, value) != true)) {
                    this.PhoneAreaCodeField = value;
                    this.RaisePropertyChanged("PhoneAreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneCountryCode {
            get {
                return this.PhoneCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneCountryCodeField, value) != true)) {
                    this.PhoneCountryCodeField = value;
                    this.RaisePropertyChanged("PhoneCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneExtension {
            get {
                return this.PhoneExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneExtensionField, value) != true)) {
                    this.PhoneExtensionField = value;
                    this.RaisePropertyChanged("PhoneExtension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Aptify.ICNETService")]
    public interface ICNETService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/RenewMembership", ReplyAction="http://tempuri.org/ICNETService/RenewMembershipResponse")]
        MemberAPI.Services.Aptify.RenewMembershipResponse RenewMembership(MemberAPI.Services.Aptify.RenewMembershipRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/RenewMembership", ReplyAction="http://tempuri.org/ICNETService/RenewMembershipResponse")]
        System.Threading.Tasks.Task<MemberAPI.Services.Aptify.RenewMembershipResponse> RenewMembershipAsync(MemberAPI.Services.Aptify.RenewMembershipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/CreateMembership", ReplyAction="http://tempuri.org/ICNETService/CreateMembershipResponse")]
        MemberAPI.Services.Aptify.CreateMembershipResponse CreateMembership(MemberAPI.Services.Aptify.CreateMembershipRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/CreateMembership", ReplyAction="http://tempuri.org/ICNETService/CreateMembershipResponse")]
        System.Threading.Tasks.Task<MemberAPI.Services.Aptify.CreateMembershipResponse> CreateMembershipAsync(MemberAPI.Services.Aptify.CreateMembershipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/NMCProcessWebApplication", ReplyAction="http://tempuri.org/ICNETService/NMCProcessWebApplicationResponse")]
        MemberAPI.Services.Aptify.NMCProcessWebApplicationResponse NMCProcessWebApplication(MemberAPI.Services.Aptify.NMCProcessWebApplicationRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/NMCProcessWebApplication", ReplyAction="http://tempuri.org/ICNETService/NMCProcessWebApplicationResponse")]
        System.Threading.Tasks.Task<MemberAPI.Services.Aptify.NMCProcessWebApplicationResponse> NMCProcessWebApplicationAsync(MemberAPI.Services.Aptify.NMCProcessWebApplicationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/RequestMembership", ReplyAction="http://tempuri.org/ICNETService/RequestMembershipResponse")]
        MemberAPI.Services.Aptify.RequestMembershipResponse RequestMembership(MemberAPI.Services.Aptify.RequestMembershipRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/RequestMembership", ReplyAction="http://tempuri.org/ICNETService/RequestMembershipResponse")]
        System.Threading.Tasks.Task<MemberAPI.Services.Aptify.RequestMembershipResponse> RequestMembershipAsync(MemberAPI.Services.Aptify.RequestMembershipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/ProcessContactLog", ReplyAction="http://tempuri.org/ICNETService/ProcessContactLogResponse")]
        MemberAPI.Services.Aptify.ProcessContactLogResponse ProcessContactLog(MemberAPI.Services.Aptify.ProcessContactLogRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/ProcessContactLog", ReplyAction="http://tempuri.org/ICNETService/ProcessContactLogResponse")]
        System.Threading.Tasks.Task<MemberAPI.Services.Aptify.ProcessContactLogResponse> ProcessContactLogAsync(MemberAPI.Services.Aptify.ProcessContactLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/ProcessAddress", ReplyAction="http://tempuri.org/ICNETService/ProcessAddressResponse")]
        MemberAPI.Services.Aptify.ProcessAddressResponse ProcessAddress(MemberAPI.Services.Aptify.ProcessAddressRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/ProcessAddress", ReplyAction="http://tempuri.org/ICNETService/ProcessAddressResponse")]
        System.Threading.Tasks.Task<MemberAPI.Services.Aptify.ProcessAddressResponse> ProcessAddressAsync(MemberAPI.Services.Aptify.ProcessAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/ProcessDependents", ReplyAction="http://tempuri.org/ICNETService/ProcessDependentsResponse")]
        MemberAPI.Services.Aptify.ProcessDependentsResponse ProcessDependents(MemberAPI.Services.Aptify.ProcessDependentsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/ProcessDependents", ReplyAction="http://tempuri.org/ICNETService/ProcessDependentsResponse")]
        System.Threading.Tasks.Task<MemberAPI.Services.Aptify.ProcessDependentsResponse> ProcessDependentsAsync(MemberAPI.Services.Aptify.ProcessDependentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/ProcessVehicle", ReplyAction="http://tempuri.org/ICNETService/ProcessVehicleResponse")]
        MemberAPI.Services.Aptify.ProcessVehicleResponse ProcessVehicle(MemberAPI.Services.Aptify.ProcessVehicleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/ProcessVehicle", ReplyAction="http://tempuri.org/ICNETService/ProcessVehicleResponse")]
        System.Threading.Tasks.Task<MemberAPI.Services.Aptify.ProcessVehicleResponse> ProcessVehicleAsync(MemberAPI.Services.Aptify.ProcessVehicleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/ProcessEmail", ReplyAction="http://tempuri.org/ICNETService/ProcessEmailResponse")]
        MemberAPI.Services.Aptify.ProcessEmailResponse ProcessEmail(MemberAPI.Services.Aptify.ProcessEmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/ProcessEmail", ReplyAction="http://tempuri.org/ICNETService/ProcessEmailResponse")]
        System.Threading.Tasks.Task<MemberAPI.Services.Aptify.ProcessEmailResponse> ProcessEmailAsync(MemberAPI.Services.Aptify.ProcessEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/ChangeSocialClubNumber", ReplyAction="http://tempuri.org/ICNETService/ChangeSocialClubNumberResponse")]
        MemberAPI.Services.Aptify.ChangeSocialClubNumberResponse ChangeSocialClubNumber(MemberAPI.Services.Aptify.ChangeSocialClubNumberRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/ChangeSocialClubNumber", ReplyAction="http://tempuri.org/ICNETService/ChangeSocialClubNumberResponse")]
        System.Threading.Tasks.Task<MemberAPI.Services.Aptify.ChangeSocialClubNumberResponse> ChangeSocialClubNumberAsync(MemberAPI.Services.Aptify.ChangeSocialClubNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/ProcessPhoneNumbers", ReplyAction="http://tempuri.org/ICNETService/ProcessPhoneNumbersResponse")]
        MemberAPI.Services.Aptify.ProcessPhoneNumbersResponse ProcessPhoneNumbers(MemberAPI.Services.Aptify.ProcessPhoneNumbersRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/ProcessPhoneNumbers", ReplyAction="http://tempuri.org/ICNETService/ProcessPhoneNumbersResponse")]
        System.Threading.Tasks.Task<MemberAPI.Services.Aptify.ProcessPhoneNumbersResponse> ProcessPhoneNumbersAsync(MemberAPI.Services.Aptify.ProcessPhoneNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/GetMemberNumbers", ReplyAction="http://tempuri.org/ICNETService/GetMemberNumbersResponse")]
        MemberAPI.Services.Aptify.GetMemberNumbersResponse GetMemberNumbers(MemberAPI.Services.Aptify.GetMemberNumbersRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/GetMemberNumbers", ReplyAction="http://tempuri.org/ICNETService/GetMemberNumbersResponse")]
        System.Threading.Tasks.Task<MemberAPI.Services.Aptify.GetMemberNumbersResponse> GetMemberNumbersAsync(MemberAPI.Services.Aptify.GetMemberNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/GetMemberNumber", ReplyAction="http://tempuri.org/ICNETService/GetMemberNumberResponse")]
        MemberAPI.Services.Aptify.GetMemberNumberResponse GetMemberNumber(MemberAPI.Services.Aptify.GetMemberNumberRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/GetMemberNumber", ReplyAction="http://tempuri.org/ICNETService/GetMemberNumberResponse")]
        System.Threading.Tasks.Task<MemberAPI.Services.Aptify.GetMemberNumberResponse> GetMemberNumberAsync(MemberAPI.Services.Aptify.GetMemberNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/ProcessSalesRep", ReplyAction="http://tempuri.org/ICNETService/ProcessSalesRepResponse")]
        MemberAPI.Services.Aptify.ProcessSalesRepResponse ProcessSalesRep(MemberAPI.Services.Aptify.ProcessSalesRepRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/ProcessSalesRep", ReplyAction="http://tempuri.org/ICNETService/ProcessSalesRepResponse")]
        System.Threading.Tasks.Task<MemberAPI.Services.Aptify.ProcessSalesRepResponse> ProcessSalesRepAsync(MemberAPI.Services.Aptify.ProcessSalesRepRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/NMCBankInfoValidtion", ReplyAction="http://tempuri.org/ICNETService/NMCBankInfoValidtionResponse")]
        MemberAPI.DAL.CNETService.NMCRoutingValidationResult NMCBankInfoValidtion(string ABA, string accountNumber, string MembershipNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/NMCBankInfoValidtion", ReplyAction="http://tempuri.org/ICNETService/NMCBankInfoValidtionResponse")]
        System.Threading.Tasks.Task<MemberAPI.DAL.CNETService.NMCRoutingValidationResult> NMCBankInfoValidtionAsync(string ABA, string accountNumber, string MembershipNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/NMCCompanySaleRepsList", ReplyAction="http://tempuri.org/ICNETService/NMCCompanySaleRepsListResponse")]
        MemberAPI.DAL.CNETService.NMCCompanySalesRepsResponse[] NMCCompanySaleRepsList(int CompanyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNETService/NMCCompanySaleRepsList", ReplyAction="http://tempuri.org/ICNETService/NMCCompanySaleRepsListResponse")]
        System.Threading.Tasks.Task<MemberAPI.DAL.CNETService.NMCCompanySalesRepsResponse[]> NMCCompanySaleRepsListAsync(int CompanyID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RenewMembership", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RenewMembershipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MemberAPI.DAL.CNETService.RenewalPayment CNETRenewalPayment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExceptionText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int RequestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public bool CommitToDB;
        
        public RenewMembershipRequest() {
        }
        
        public RenewMembershipRequest(MemberAPI.DAL.CNETService.RenewalPayment CNETRenewalPayment, string ExceptionText, int RequestID, bool CommitToDB) {
            this.CNETRenewalPayment = CNETRenewalPayment;
            this.ExceptionText = ExceptionText;
            this.RequestID = RequestID;
            this.CommitToDB = CommitToDB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RenewMembershipResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RenewMembershipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RenewMembershipResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExceptionText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int RequestID;
        
        public RenewMembershipResponse() {
        }
        
        public RenewMembershipResponse(bool RenewMembershipResult, string ExceptionText, int RequestID) {
            this.RenewMembershipResult = RenewMembershipResult;
            this.ExceptionText = ExceptionText;
            this.RequestID = RequestID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMembership", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateMembershipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MemberAPI.DAL.CNETService.Membership CNETMembership;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public MemberAPI.DAL.CNETService.EnumMembershipType CNETMembershipType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ExceptionText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int RequestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public bool CommitToDB;
        
        public CreateMembershipRequest() {
        }
        
        public CreateMembershipRequest(MemberAPI.DAL.CNETService.Membership CNETMembership, MemberAPI.DAL.CNETService.EnumMembershipType CNETMembershipType, string ExceptionText, int RequestID, bool CommitToDB) {
            this.CNETMembership = CNETMembership;
            this.CNETMembershipType = CNETMembershipType;
            this.ExceptionText = ExceptionText;
            this.RequestID = RequestID;
            this.CommitToDB = CommitToDB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMembershipResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateMembershipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreateMembershipResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExceptionText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int RequestID;
        
        public CreateMembershipResponse() {
        }
        
        public CreateMembershipResponse(bool CreateMembershipResult, string ExceptionText, int RequestID) {
            this.CreateMembershipResult = CreateMembershipResult;
            this.ExceptionText = ExceptionText;
            this.RequestID = RequestID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NMCProcessWebApplication", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NMCProcessWebApplicationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sApplicationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sErrorDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sNMCMembershipNumber;
        
        public NMCProcessWebApplicationRequest() {
        }
        
        public NMCProcessWebApplicationRequest(string sApplicationID, string sErrorDescription, string sNMCMembershipNumber) {
            this.sApplicationID = sApplicationID;
            this.sErrorDescription = sErrorDescription;
            this.sNMCMembershipNumber = sNMCMembershipNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NMCProcessWebApplicationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NMCProcessWebApplicationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool NMCProcessWebApplicationResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sErrorDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sNMCMembershipNumber;
        
        public NMCProcessWebApplicationResponse() {
        }
        
        public NMCProcessWebApplicationResponse(bool NMCProcessWebApplicationResult, string sErrorDescription, string sNMCMembershipNumber) {
            this.NMCProcessWebApplicationResult = NMCProcessWebApplicationResult;
            this.sErrorDescription = sErrorDescription;
            this.sNMCMembershipNumber = sNMCMembershipNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestMembership", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RequestMembershipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string MembershipNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public MemberAPI.DAL.CNETService.EnumMembershipType CNETMembershipType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ExceptionText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int RequestID;
        
        public RequestMembershipRequest() {
        }
        
        public RequestMembershipRequest(string MembershipNumber, MemberAPI.DAL.CNETService.EnumMembershipType CNETMembershipType, string ExceptionText, int RequestID) {
            this.MembershipNumber = MembershipNumber;
            this.CNETMembershipType = CNETMembershipType;
            this.ExceptionText = ExceptionText;
            this.RequestID = RequestID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestMembershipResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RequestMembershipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RequestMembershipResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExceptionText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int RequestID;
        
        public RequestMembershipResponse() {
        }
        
        public RequestMembershipResponse(bool RequestMembershipResult, string ExceptionText, int RequestID) {
            this.RequestMembershipResult = RequestMembershipResult;
            this.ExceptionText = ExceptionText;
            this.RequestID = RequestID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessContactLog", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessContactLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string MembershipNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Comments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string SaleChannelName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string ExceptionText;
        
        public ProcessContactLogRequest() {
        }
        
        public ProcessContactLogRequest(string MembershipNumber, string Description, string Comments, string SaleChannelName, string ExceptionText) {
            this.MembershipNumber = MembershipNumber;
            this.Description = Description;
            this.Comments = Comments;
            this.SaleChannelName = SaleChannelName;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessContactLogResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessContactLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ProcessContactLogResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExceptionText;
        
        public ProcessContactLogResponse() {
        }
        
        public ProcessContactLogResponse(bool ProcessContactLogResult, string ExceptionText) {
            this.ProcessContactLogResult = ProcessContactLogResult;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessAddress", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string MembershipNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public MemberAPI.DAL.CNETService.Address CNETAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ExceptionText;
        
        public ProcessAddressRequest() {
        }
        
        public ProcessAddressRequest(string MembershipNumber, MemberAPI.DAL.CNETService.Address CNETAddress, string ExceptionText) {
            this.MembershipNumber = MembershipNumber;
            this.CNETAddress = CNETAddress;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessAddressResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ProcessAddressResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExceptionText;
        
        public ProcessAddressResponse() {
        }
        
        public ProcessAddressResponse(bool ProcessAddressResult, string ExceptionText) {
            this.ProcessAddressResult = ProcessAddressResult;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessDependents", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessDependentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string MembershipNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public MemberAPI.DAL.CNETService.MemberDependent[] Dependents;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ExceptionText;
        
        public ProcessDependentsRequest() {
        }
        
        public ProcessDependentsRequest(string MembershipNumber, MemberAPI.DAL.CNETService.MemberDependent[] Dependents, string ExceptionText) {
            this.MembershipNumber = MembershipNumber;
            this.Dependents = Dependents;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessDependentsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessDependentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ProcessDependentsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExceptionText;
        
        public ProcessDependentsResponse() {
        }
        
        public ProcessDependentsResponse(bool ProcessDependentsResult, string ExceptionText) {
            this.ProcessDependentsResult = ProcessDependentsResult;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessVehicle", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessVehicleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string MembershipNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public MemberAPI.DAL.CNETService.VehicleInformation CNETVehicleInformation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ExceptionText;
        
        public ProcessVehicleRequest() {
        }
        
        public ProcessVehicleRequest(string MembershipNumber, MemberAPI.DAL.CNETService.VehicleInformation CNETVehicleInformation, string ExceptionText) {
            this.MembershipNumber = MembershipNumber;
            this.CNETVehicleInformation = CNETVehicleInformation;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessVehicleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessVehicleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ProcessVehicleResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExceptionText;
        
        public ProcessVehicleResponse() {
        }
        
        public ProcessVehicleResponse(bool ProcessVehicleResult, string ExceptionText) {
            this.ProcessVehicleResult = ProcessVehicleResult;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string MembershipNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string EmailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool Primary;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ExceptionText;
        
        public ProcessEmailRequest() {
        }
        
        public ProcessEmailRequest(string MembershipNumber, string EmailAddress, bool Primary, string ExceptionText) {
            this.MembershipNumber = MembershipNumber;
            this.EmailAddress = EmailAddress;
            this.Primary = Primary;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ProcessEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExceptionText;
        
        public ProcessEmailResponse() {
        }
        
        public ProcessEmailResponse(bool ProcessEmailResult, string ExceptionText) {
            this.ProcessEmailResult = ProcessEmailResult;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeSocialClubNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangeSocialClubNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string MembershipNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int AffiliateID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SocialClubNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ExceptionText;
        
        public ChangeSocialClubNumberRequest() {
        }
        
        public ChangeSocialClubNumberRequest(string MembershipNumber, int AffiliateID, string SocialClubNumber, string ExceptionText) {
            this.MembershipNumber = MembershipNumber;
            this.AffiliateID = AffiliateID;
            this.SocialClubNumber = SocialClubNumber;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeSocialClubNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangeSocialClubNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ChangeSocialClubNumberResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExceptionText;
        
        public ChangeSocialClubNumberResponse() {
        }
        
        public ChangeSocialClubNumberResponse(bool ChangeSocialClubNumberResult, string ExceptionText) {
            this.ChangeSocialClubNumberResult = ChangeSocialClubNumberResult;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessPhoneNumbers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessPhoneNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string MembershipNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public MemberAPI.DAL.CNETService.PhoneNumber[] PhoneNumbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ExceptionText;
        
        public ProcessPhoneNumbersRequest() {
        }
        
        public ProcessPhoneNumbersRequest(string MembershipNumber, MemberAPI.DAL.CNETService.PhoneNumber[] PhoneNumbers, string ExceptionText) {
            this.MembershipNumber = MembershipNumber;
            this.PhoneNumbers = PhoneNumbers;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessPhoneNumbersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessPhoneNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ProcessPhoneNumbersResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExceptionText;
        
        public ProcessPhoneNumbersResponse() {
        }
        
        public ProcessPhoneNumbersResponse(bool ProcessPhoneNumbersResult, string ExceptionText) {
            this.ProcessPhoneNumbersResult = ProcessPhoneNumbersResult;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMemberNumbers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMemberNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int NumOfMemberNumbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExceptionText;
        
        public GetMemberNumbersRequest() {
        }
        
        public GetMemberNumbersRequest(int NumOfMemberNumbers, string ExceptionText) {
            this.NumOfMemberNumbers = NumOfMemberNumbers;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMemberNumbersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMemberNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MemberAPI.DAL.CNETService.MemberNumbers[] GetMemberNumbersResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExceptionText;
        
        public GetMemberNumbersResponse() {
        }
        
        public GetMemberNumbersResponse(MemberAPI.DAL.CNETService.MemberNumbers[] GetMemberNumbersResult, string ExceptionText) {
            this.GetMemberNumbersResult = GetMemberNumbersResult;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMemberNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMemberNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ExceptionText;
        
        public GetMemberNumberRequest() {
        }
        
        public GetMemberNumberRequest(string ExceptionText) {
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMemberNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMemberNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetMemberNumberResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExceptionText;
        
        public GetMemberNumberResponse() {
        }
        
        public GetMemberNumberResponse(string GetMemberNumberResult, string ExceptionText) {
            this.GetMemberNumberResult = GetMemberNumberResult;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessSalesRep", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessSalesRepRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MemberAPI.Services.Aptify.SalesRep salesRep;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExceptionText;
        
        public ProcessSalesRepRequest() {
        }
        
        public ProcessSalesRepRequest(MemberAPI.Services.Aptify.SalesRep salesRep, string ExceptionText) {
            this.salesRep = salesRep;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessSalesRepResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessSalesRepResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long ProcessSalesRepResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ExceptionText;
        
        public ProcessSalesRepResponse() {
        }
        
        public ProcessSalesRepResponse(long ProcessSalesRepResult, string ExceptionText) {
            this.ProcessSalesRepResult = ProcessSalesRepResult;
            this.ExceptionText = ExceptionText;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICNETServiceChannel : MemberAPI.Services.Aptify.ICNETService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CNETServiceClient : System.ServiceModel.ClientBase<MemberAPI.Services.Aptify.ICNETService>, MemberAPI.Services.Aptify.ICNETService {
        
        public CNETServiceClient() {
        }
        
        public CNETServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CNETServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CNETServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CNETServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberAPI.Services.Aptify.RenewMembershipResponse MemberAPI.Services.Aptify.ICNETService.RenewMembership(MemberAPI.Services.Aptify.RenewMembershipRequest request) {
            return base.Channel.RenewMembership(request);
        }
        
        public bool RenewMembership(MemberAPI.DAL.CNETService.RenewalPayment CNETRenewalPayment, ref string ExceptionText, ref int RequestID, bool CommitToDB) {
            MemberAPI.Services.Aptify.RenewMembershipRequest inValue = new MemberAPI.Services.Aptify.RenewMembershipRequest();
            inValue.CNETRenewalPayment = CNETRenewalPayment;
            inValue.ExceptionText = ExceptionText;
            inValue.RequestID = RequestID;
            inValue.CommitToDB = CommitToDB;
            MemberAPI.Services.Aptify.RenewMembershipResponse retVal = ((MemberAPI.Services.Aptify.ICNETService)(this)).RenewMembership(inValue);
            ExceptionText = retVal.ExceptionText;
            RequestID = retVal.RequestID;
            return retVal.RenewMembershipResult;
        }
        
        public System.Threading.Tasks.Task<MemberAPI.Services.Aptify.RenewMembershipResponse> RenewMembershipAsync(MemberAPI.Services.Aptify.RenewMembershipRequest request) {
            return base.Channel.RenewMembershipAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberAPI.Services.Aptify.CreateMembershipResponse MemberAPI.Services.Aptify.ICNETService.CreateMembership(MemberAPI.Services.Aptify.CreateMembershipRequest request) {
            return base.Channel.CreateMembership(request);
        }
        
        public bool CreateMembership(MemberAPI.DAL.CNETService.Membership CNETMembership, MemberAPI.DAL.CNETService.EnumMembershipType CNETMembershipType, ref string ExceptionText, ref int RequestID, bool CommitToDB) {
            MemberAPI.Services.Aptify.CreateMembershipRequest inValue = new MemberAPI.Services.Aptify.CreateMembershipRequest();
            inValue.CNETMembership = CNETMembership;
            inValue.CNETMembershipType = CNETMembershipType;
            inValue.ExceptionText = ExceptionText;
            inValue.RequestID = RequestID;
            inValue.CommitToDB = CommitToDB;
            MemberAPI.Services.Aptify.CreateMembershipResponse retVal = ((MemberAPI.Services.Aptify.ICNETService)(this)).CreateMembership(inValue);
            ExceptionText = retVal.ExceptionText;
            RequestID = retVal.RequestID;
            return retVal.CreateMembershipResult;
        }
        
        public System.Threading.Tasks.Task<MemberAPI.Services.Aptify.CreateMembershipResponse> CreateMembershipAsync(MemberAPI.Services.Aptify.CreateMembershipRequest request) {
            return base.Channel.CreateMembershipAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberAPI.Services.Aptify.NMCProcessWebApplicationResponse MemberAPI.Services.Aptify.ICNETService.NMCProcessWebApplication(MemberAPI.Services.Aptify.NMCProcessWebApplicationRequest request) {
            return base.Channel.NMCProcessWebApplication(request);
        }
        
        public bool NMCProcessWebApplication(string sApplicationID, ref string sErrorDescription, ref string sNMCMembershipNumber) {
            MemberAPI.Services.Aptify.NMCProcessWebApplicationRequest inValue = new MemberAPI.Services.Aptify.NMCProcessWebApplicationRequest();
            inValue.sApplicationID = sApplicationID;
            inValue.sErrorDescription = sErrorDescription;
            inValue.sNMCMembershipNumber = sNMCMembershipNumber;
            MemberAPI.Services.Aptify.NMCProcessWebApplicationResponse retVal = ((MemberAPI.Services.Aptify.ICNETService)(this)).NMCProcessWebApplication(inValue);
            sErrorDescription = retVal.sErrorDescription;
            sNMCMembershipNumber = retVal.sNMCMembershipNumber;
            return retVal.NMCProcessWebApplicationResult;
        }
        
        public System.Threading.Tasks.Task<MemberAPI.Services.Aptify.NMCProcessWebApplicationResponse> NMCProcessWebApplicationAsync(MemberAPI.Services.Aptify.NMCProcessWebApplicationRequest request) {
            return base.Channel.NMCProcessWebApplicationAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberAPI.Services.Aptify.RequestMembershipResponse MemberAPI.Services.Aptify.ICNETService.RequestMembership(MemberAPI.Services.Aptify.RequestMembershipRequest request) {
            return base.Channel.RequestMembership(request);
        }
        
        public bool RequestMembership(string MembershipNumber, MemberAPI.DAL.CNETService.EnumMembershipType CNETMembershipType, ref string ExceptionText, ref int RequestID) {
            MemberAPI.Services.Aptify.RequestMembershipRequest inValue = new MemberAPI.Services.Aptify.RequestMembershipRequest();
            inValue.MembershipNumber = MembershipNumber;
            inValue.CNETMembershipType = CNETMembershipType;
            inValue.ExceptionText = ExceptionText;
            inValue.RequestID = RequestID;
            MemberAPI.Services.Aptify.RequestMembershipResponse retVal = ((MemberAPI.Services.Aptify.ICNETService)(this)).RequestMembership(inValue);
            ExceptionText = retVal.ExceptionText;
            RequestID = retVal.RequestID;
            return retVal.RequestMembershipResult;
        }
        
        public System.Threading.Tasks.Task<MemberAPI.Services.Aptify.RequestMembershipResponse> RequestMembershipAsync(MemberAPI.Services.Aptify.RequestMembershipRequest request) {
            return base.Channel.RequestMembershipAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberAPI.Services.Aptify.ProcessContactLogResponse MemberAPI.Services.Aptify.ICNETService.ProcessContactLog(MemberAPI.Services.Aptify.ProcessContactLogRequest request) {
            return base.Channel.ProcessContactLog(request);
        }
        
        public bool ProcessContactLog(string MembershipNumber, string Description, string Comments, string SaleChannelName, ref string ExceptionText) {
            MemberAPI.Services.Aptify.ProcessContactLogRequest inValue = new MemberAPI.Services.Aptify.ProcessContactLogRequest();
            inValue.MembershipNumber = MembershipNumber;
            inValue.Description = Description;
            inValue.Comments = Comments;
            inValue.SaleChannelName = SaleChannelName;
            inValue.ExceptionText = ExceptionText;
            MemberAPI.Services.Aptify.ProcessContactLogResponse retVal = ((MemberAPI.Services.Aptify.ICNETService)(this)).ProcessContactLog(inValue);
            ExceptionText = retVal.ExceptionText;
            return retVal.ProcessContactLogResult;
        }
        
        public System.Threading.Tasks.Task<MemberAPI.Services.Aptify.ProcessContactLogResponse> ProcessContactLogAsync(MemberAPI.Services.Aptify.ProcessContactLogRequest request) {
            return base.Channel.ProcessContactLogAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberAPI.Services.Aptify.ProcessAddressResponse MemberAPI.Services.Aptify.ICNETService.ProcessAddress(MemberAPI.Services.Aptify.ProcessAddressRequest request) {
            return base.Channel.ProcessAddress(request);
        }
        
        public bool ProcessAddress(string MembershipNumber, MemberAPI.DAL.CNETService.Address CNETAddress, ref string ExceptionText) {
            MemberAPI.Services.Aptify.ProcessAddressRequest inValue = new MemberAPI.Services.Aptify.ProcessAddressRequest();
            inValue.MembershipNumber = MembershipNumber;
            inValue.CNETAddress = CNETAddress;
            inValue.ExceptionText = ExceptionText;
            MemberAPI.Services.Aptify.ProcessAddressResponse retVal = ((MemberAPI.Services.Aptify.ICNETService)(this)).ProcessAddress(inValue);
            ExceptionText = retVal.ExceptionText;
            return retVal.ProcessAddressResult;
        }
        
        public System.Threading.Tasks.Task<MemberAPI.Services.Aptify.ProcessAddressResponse> ProcessAddressAsync(MemberAPI.Services.Aptify.ProcessAddressRequest request) {
            return base.Channel.ProcessAddressAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberAPI.Services.Aptify.ProcessDependentsResponse MemberAPI.Services.Aptify.ICNETService.ProcessDependents(MemberAPI.Services.Aptify.ProcessDependentsRequest request) {
            return base.Channel.ProcessDependents(request);
        }
        
        public bool ProcessDependents(string MembershipNumber, MemberAPI.DAL.CNETService.MemberDependent[] Dependents, ref string ExceptionText) {
            MemberAPI.Services.Aptify.ProcessDependentsRequest inValue = new MemberAPI.Services.Aptify.ProcessDependentsRequest();
            inValue.MembershipNumber = MembershipNumber;
            inValue.Dependents = Dependents;
            inValue.ExceptionText = ExceptionText;
            MemberAPI.Services.Aptify.ProcessDependentsResponse retVal = ((MemberAPI.Services.Aptify.ICNETService)(this)).ProcessDependents(inValue);
            ExceptionText = retVal.ExceptionText;
            return retVal.ProcessDependentsResult;
        }
        
        public System.Threading.Tasks.Task<MemberAPI.Services.Aptify.ProcessDependentsResponse> ProcessDependentsAsync(MemberAPI.Services.Aptify.ProcessDependentsRequest request) {
            return base.Channel.ProcessDependentsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberAPI.Services.Aptify.ProcessVehicleResponse MemberAPI.Services.Aptify.ICNETService.ProcessVehicle(MemberAPI.Services.Aptify.ProcessVehicleRequest request) {
            return base.Channel.ProcessVehicle(request);
        }
        
        public bool ProcessVehicle(string MembershipNumber, MemberAPI.DAL.CNETService.VehicleInformation CNETVehicleInformation, ref string ExceptionText) {
            MemberAPI.Services.Aptify.ProcessVehicleRequest inValue = new MemberAPI.Services.Aptify.ProcessVehicleRequest();
            inValue.MembershipNumber = MembershipNumber;
            inValue.CNETVehicleInformation = CNETVehicleInformation;
            inValue.ExceptionText = ExceptionText;
            MemberAPI.Services.Aptify.ProcessVehicleResponse retVal = ((MemberAPI.Services.Aptify.ICNETService)(this)).ProcessVehicle(inValue);
            ExceptionText = retVal.ExceptionText;
            return retVal.ProcessVehicleResult;
        }
        
        public System.Threading.Tasks.Task<MemberAPI.Services.Aptify.ProcessVehicleResponse> ProcessVehicleAsync(MemberAPI.Services.Aptify.ProcessVehicleRequest request) {
            return base.Channel.ProcessVehicleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberAPI.Services.Aptify.ProcessEmailResponse MemberAPI.Services.Aptify.ICNETService.ProcessEmail(MemberAPI.Services.Aptify.ProcessEmailRequest request) {
            return base.Channel.ProcessEmail(request);
        }
        
        public bool ProcessEmail(string MembershipNumber, string EmailAddress, bool Primary, ref string ExceptionText) {
            MemberAPI.Services.Aptify.ProcessEmailRequest inValue = new MemberAPI.Services.Aptify.ProcessEmailRequest();
            inValue.MembershipNumber = MembershipNumber;
            inValue.EmailAddress = EmailAddress;
            inValue.Primary = Primary;
            inValue.ExceptionText = ExceptionText;
            MemberAPI.Services.Aptify.ProcessEmailResponse retVal = ((MemberAPI.Services.Aptify.ICNETService)(this)).ProcessEmail(inValue);
            ExceptionText = retVal.ExceptionText;
            return retVal.ProcessEmailResult;
        }
        
        public System.Threading.Tasks.Task<MemberAPI.Services.Aptify.ProcessEmailResponse> ProcessEmailAsync(MemberAPI.Services.Aptify.ProcessEmailRequest request) {
            return base.Channel.ProcessEmailAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberAPI.Services.Aptify.ChangeSocialClubNumberResponse MemberAPI.Services.Aptify.ICNETService.ChangeSocialClubNumber(MemberAPI.Services.Aptify.ChangeSocialClubNumberRequest request) {
            return base.Channel.ChangeSocialClubNumber(request);
        }
        
        public bool ChangeSocialClubNumber(string MembershipNumber, int AffiliateID, string SocialClubNumber, ref string ExceptionText) {
            MemberAPI.Services.Aptify.ChangeSocialClubNumberRequest inValue = new MemberAPI.Services.Aptify.ChangeSocialClubNumberRequest();
            inValue.MembershipNumber = MembershipNumber;
            inValue.AffiliateID = AffiliateID;
            inValue.SocialClubNumber = SocialClubNumber;
            inValue.ExceptionText = ExceptionText;
            MemberAPI.Services.Aptify.ChangeSocialClubNumberResponse retVal = ((MemberAPI.Services.Aptify.ICNETService)(this)).ChangeSocialClubNumber(inValue);
            ExceptionText = retVal.ExceptionText;
            return retVal.ChangeSocialClubNumberResult;
        }
        
        public System.Threading.Tasks.Task<MemberAPI.Services.Aptify.ChangeSocialClubNumberResponse> ChangeSocialClubNumberAsync(MemberAPI.Services.Aptify.ChangeSocialClubNumberRequest request) {
            return base.Channel.ChangeSocialClubNumberAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberAPI.Services.Aptify.ProcessPhoneNumbersResponse MemberAPI.Services.Aptify.ICNETService.ProcessPhoneNumbers(MemberAPI.Services.Aptify.ProcessPhoneNumbersRequest request) {
            return base.Channel.ProcessPhoneNumbers(request);
        }
        
        public bool ProcessPhoneNumbers(string MembershipNumber, MemberAPI.DAL.CNETService.PhoneNumber[] PhoneNumbers, ref string ExceptionText) {
            MemberAPI.Services.Aptify.ProcessPhoneNumbersRequest inValue = new MemberAPI.Services.Aptify.ProcessPhoneNumbersRequest();
            inValue.MembershipNumber = MembershipNumber;
            inValue.PhoneNumbers = PhoneNumbers;
            inValue.ExceptionText = ExceptionText;
            MemberAPI.Services.Aptify.ProcessPhoneNumbersResponse retVal = ((MemberAPI.Services.Aptify.ICNETService)(this)).ProcessPhoneNumbers(inValue);
            ExceptionText = retVal.ExceptionText;
            return retVal.ProcessPhoneNumbersResult;
        }
        
        public System.Threading.Tasks.Task<MemberAPI.Services.Aptify.ProcessPhoneNumbersResponse> ProcessPhoneNumbersAsync(MemberAPI.Services.Aptify.ProcessPhoneNumbersRequest request) {
            return base.Channel.ProcessPhoneNumbersAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberAPI.Services.Aptify.GetMemberNumbersResponse MemberAPI.Services.Aptify.ICNETService.GetMemberNumbers(MemberAPI.Services.Aptify.GetMemberNumbersRequest request) {
            return base.Channel.GetMemberNumbers(request);
        }
        
        public MemberAPI.DAL.CNETService.MemberNumbers[] GetMemberNumbers(int NumOfMemberNumbers, ref string ExceptionText) {
            MemberAPI.Services.Aptify.GetMemberNumbersRequest inValue = new MemberAPI.Services.Aptify.GetMemberNumbersRequest();
            inValue.NumOfMemberNumbers = NumOfMemberNumbers;
            inValue.ExceptionText = ExceptionText;
            MemberAPI.Services.Aptify.GetMemberNumbersResponse retVal = ((MemberAPI.Services.Aptify.ICNETService)(this)).GetMemberNumbers(inValue);
            ExceptionText = retVal.ExceptionText;
            return retVal.GetMemberNumbersResult;
        }
        
        public System.Threading.Tasks.Task<MemberAPI.Services.Aptify.GetMemberNumbersResponse> GetMemberNumbersAsync(MemberAPI.Services.Aptify.GetMemberNumbersRequest request) {
            return base.Channel.GetMemberNumbersAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberAPI.Services.Aptify.GetMemberNumberResponse MemberAPI.Services.Aptify.ICNETService.GetMemberNumber(MemberAPI.Services.Aptify.GetMemberNumberRequest request) {
            return base.Channel.GetMemberNumber(request);
        }
        
        public string GetMemberNumber(ref string ExceptionText) {
            MemberAPI.Services.Aptify.GetMemberNumberRequest inValue = new MemberAPI.Services.Aptify.GetMemberNumberRequest();
            inValue.ExceptionText = ExceptionText;
            MemberAPI.Services.Aptify.GetMemberNumberResponse retVal = ((MemberAPI.Services.Aptify.ICNETService)(this)).GetMemberNumber(inValue);
            ExceptionText = retVal.ExceptionText;
            return retVal.GetMemberNumberResult;
        }
        
        public System.Threading.Tasks.Task<MemberAPI.Services.Aptify.GetMemberNumberResponse> GetMemberNumberAsync(MemberAPI.Services.Aptify.GetMemberNumberRequest request) {
            return base.Channel.GetMemberNumberAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MemberAPI.Services.Aptify.ProcessSalesRepResponse MemberAPI.Services.Aptify.ICNETService.ProcessSalesRep(MemberAPI.Services.Aptify.ProcessSalesRepRequest request) {
            return base.Channel.ProcessSalesRep(request);
        }
        
        public long ProcessSalesRep(MemberAPI.Services.Aptify.SalesRep salesRep, ref string ExceptionText) {
            MemberAPI.Services.Aptify.ProcessSalesRepRequest inValue = new MemberAPI.Services.Aptify.ProcessSalesRepRequest();
            inValue.salesRep = salesRep;
            inValue.ExceptionText = ExceptionText;
            MemberAPI.Services.Aptify.ProcessSalesRepResponse retVal = ((MemberAPI.Services.Aptify.ICNETService)(this)).ProcessSalesRep(inValue);
            ExceptionText = retVal.ExceptionText;
            return retVal.ProcessSalesRepResult;
        }
        
        public System.Threading.Tasks.Task<MemberAPI.Services.Aptify.ProcessSalesRepResponse> ProcessSalesRepAsync(MemberAPI.Services.Aptify.ProcessSalesRepRequest request) {
            return base.Channel.ProcessSalesRepAsync(request);
        }
        
        public MemberAPI.DAL.CNETService.NMCRoutingValidationResult NMCBankInfoValidtion(string ABA, string accountNumber, string MembershipNo) {
            return base.Channel.NMCBankInfoValidtion(ABA, accountNumber, MembershipNo);
        }
        
        public System.Threading.Tasks.Task<MemberAPI.DAL.CNETService.NMCRoutingValidationResult> NMCBankInfoValidtionAsync(string ABA, string accountNumber, string MembershipNo) {
            return base.Channel.NMCBankInfoValidtionAsync(ABA, accountNumber, MembershipNo);
        }
        
        public MemberAPI.DAL.CNETService.NMCCompanySalesRepsResponse[] NMCCompanySaleRepsList(int CompanyID) {
            return base.Channel.NMCCompanySaleRepsList(CompanyID);
        }
        
        public System.Threading.Tasks.Task<MemberAPI.DAL.CNETService.NMCCompanySalesRepsResponse[]> NMCCompanySaleRepsListAsync(int CompanyID) {
            return base.Channel.NMCCompanySaleRepsListAsync(CompanyID);
        }
    }
}
