//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.BLL.WSCreditCardService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaleRequest", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
    [System.SerializableAttribute()]
    public partial class SaleRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingAddress1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingAddress2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificatePasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ChargeTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CvmNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseAvsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseCvmField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingAddress1 {
            get {
                return this.BillingAddress1Field;
            }
            set {
                if ((object.ReferenceEquals(this.BillingAddress1Field, value) != true)) {
                    this.BillingAddress1Field = value;
                    this.RaisePropertyChanged("BillingAddress1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingAddress2 {
            get {
                return this.BillingAddress2Field;
            }
            set {
                if ((object.ReferenceEquals(this.BillingAddress2Field, value) != true)) {
                    this.BillingAddress2Field = value;
                    this.RaisePropertyChanged("BillingAddress2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingCity {
            get {
                return this.BillingCityField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingCityField, value) != true)) {
                    this.BillingCityField = value;
                    this.RaisePropertyChanged("BillingCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingCountry {
            get {
                return this.BillingCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingCountryField, value) != true)) {
                    this.BillingCountryField = value;
                    this.RaisePropertyChanged("BillingCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingName {
            get {
                return this.BillingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingNameField, value) != true)) {
                    this.BillingNameField = value;
                    this.RaisePropertyChanged("BillingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingState {
            get {
                return this.BillingStateField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingStateField, value) != true)) {
                    this.BillingStateField = value;
                    this.RaisePropertyChanged("BillingState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingZip {
            get {
                return this.BillingZipField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingZipField, value) != true)) {
                    this.BillingZipField = value;
                    this.RaisePropertyChanged("BillingZip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificatePassword {
            get {
                return this.CertificatePasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificatePasswordField, value) != true)) {
                    this.CertificatePasswordField = value;
                    this.RaisePropertyChanged("CertificatePassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ChargeTotal {
            get {
                return this.ChargeTotalField;
            }
            set {
                if ((this.ChargeTotalField.Equals(value) != true)) {
                    this.ChargeTotalField = value;
                    this.RaisePropertyChanged("ChargeTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CvmNumber {
            get {
                return this.CvmNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CvmNumberField, value) != true)) {
                    this.CvmNumberField = value;
                    this.RaisePropertyChanged("CvmNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber {
            get {
                return this.ReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNumberField, value) != true)) {
                    this.ReferenceNumberField = value;
                    this.RaisePropertyChanged("ReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreNumber {
            get {
                return this.StoreNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreNumberField, value) != true)) {
                    this.StoreNumberField = value;
                    this.RaisePropertyChanged("StoreNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseAvs {
            get {
                return this.UseAvsField;
            }
            set {
                if ((this.UseAvsField.Equals(value) != true)) {
                    this.UseAvsField = value;
                    this.RaisePropertyChanged("UseAvs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseCvm {
            get {
                return this.UseCvmField;
            }
            set {
                if ((this.UseCvmField.Equals(value) != true)) {
                    this.UseCvmField = value;
                    this.RaisePropertyChanged("UseCvm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessorResponse", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
    [System.SerializableAttribute()]
    public partial class ProcessorResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApprovalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvsMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Martex.DMS.BLL.WSCreditCardService.AvsStatus AvsStatusValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CvmMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Martex.DMS.BLL.WSCreditCardService.CvmStatus CvmStatusValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessorReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessorResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Martex.DMS.BLL.WSCreditCardService.ResponseMessage ProcessorResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Martex.DMS.BLL.WSCreditCardService.TransactionResult ProcessorTransactionResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransactionDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApprovalCode {
            get {
                return this.ApprovalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovalCodeField, value) != true)) {
                    this.ApprovalCodeField = value;
                    this.RaisePropertyChanged("ApprovalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvsMessage {
            get {
                return this.AvsMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AvsMessageField, value) != true)) {
                    this.AvsMessageField = value;
                    this.RaisePropertyChanged("AvsMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Martex.DMS.BLL.WSCreditCardService.AvsStatus AvsStatusValue {
            get {
                return this.AvsStatusValueField;
            }
            set {
                if ((this.AvsStatusValueField.Equals(value) != true)) {
                    this.AvsStatusValueField = value;
                    this.RaisePropertyChanged("AvsStatusValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CvmMessage {
            get {
                return this.CvmMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.CvmMessageField, value) != true)) {
                    this.CvmMessageField = value;
                    this.RaisePropertyChanged("CvmMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Martex.DMS.BLL.WSCreditCardService.CvmStatus CvmStatusValue {
            get {
                return this.CvmStatusValueField;
            }
            set {
                if ((this.CvmStatusValueField.Equals(value) != true)) {
                    this.CvmStatusValueField = value;
                    this.RaisePropertyChanged("CvmStatusValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessorReferenceNumber {
            get {
                return this.ProcessorReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessorReferenceNumberField, value) != true)) {
                    this.ProcessorReferenceNumberField = value;
                    this.RaisePropertyChanged("ProcessorReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessorResponseCode {
            get {
                return this.ProcessorResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessorResponseCodeField, value) != true)) {
                    this.ProcessorResponseCodeField = value;
                    this.RaisePropertyChanged("ProcessorResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Martex.DMS.BLL.WSCreditCardService.ResponseMessage ProcessorResponseMessage {
            get {
                return this.ProcessorResponseMessageField;
            }
            set {
                if ((this.ProcessorResponseMessageField.Equals(value) != true)) {
                    this.ProcessorResponseMessageField = value;
                    this.RaisePropertyChanged("ProcessorResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Martex.DMS.BLL.WSCreditCardService.TransactionResult ProcessorTransactionResult {
            get {
                return this.ProcessorTransactionResultField;
            }
            set {
                if ((this.ProcessorTransactionResultField.Equals(value) != true)) {
                    this.ProcessorTransactionResultField = value;
                    this.RaisePropertyChanged("ProcessorTransactionResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TDate {
            get {
                return this.TDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TDateField, value) != true)) {
                    this.TDateField = value;
                    this.RaisePropertyChanged("TDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionDateTime {
            get {
                return this.TransactionDateTimeField;
            }
            set {
                if ((this.TransactionDateTimeField.Equals(value) != true)) {
                    this.TransactionDateTimeField = value;
                    this.RaisePropertyChanged("TransactionDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvsStatus", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
    public enum AvsStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddressZipMatch = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AddressOnlyMatch = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZipOnlyMatch = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoMatch = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CvmStatus", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
    public enum CvmStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Match = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoMatch = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
    public enum ResponseMessage : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Declined = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Accepted = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionResult", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
    public enum TransactionResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Declined = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fraud = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Duplicate = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Submitted = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessorFaultException", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
    [System.SerializableAttribute()]
    public partial class ProcessorFaultException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<object, object> ProcessorDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageText {
            get {
                return this.MessageTextField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTextField, value) != true)) {
                    this.MessageTextField = value;
                    this.RaisePropertyChanged("MessageText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<object, object> ProcessorData {
            get {
                return this.ProcessorDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessorDataField, value) != true)) {
                    this.ProcessorDataField = value;
                    this.RaisePropertyChanged("ProcessorData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericFaultException", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
    [System.SerializableAttribute()]
    public partial class GenericFaultException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageText {
            get {
                return this.MessageTextField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTextField, value) != true)) {
                    this.MessageTextField = value;
                    this.RaisePropertyChanged("MessageText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostAuthorizationRequest", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
    [System.SerializableAttribute()]
    public partial class PostAuthorizationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificatePasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ChargeTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificatePassword {
            get {
                return this.CertificatePasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificatePasswordField, value) != true)) {
                    this.CertificatePasswordField = value;
                    this.RaisePropertyChanged("CertificatePassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ChargeTotal {
            get {
                return this.ChargeTotalField;
            }
            set {
                if ((this.ChargeTotalField.Equals(value) != true)) {
                    this.ChargeTotalField = value;
                    this.RaisePropertyChanged("ChargeTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreNumber {
            get {
                return this.StoreNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreNumberField, value) != true)) {
                    this.StoreNumberField = value;
                    this.RaisePropertyChanged("StoreNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoidRequest", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
    [System.SerializableAttribute()]
    public partial class VoidRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificatePasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificatePassword {
            get {
                return this.CertificatePasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificatePasswordField, value) != true)) {
                    this.CertificatePasswordField = value;
                    this.RaisePropertyChanged("CertificatePassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreNumber {
            get {
                return this.StoreNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreNumberField, value) != true)) {
                    this.StoreNumberField = value;
                    this.RaisePropertyChanged("StoreNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TDate {
            get {
                return this.TDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TDateField, value) != true)) {
                    this.TDateField = value;
                    this.RaisePropertyChanged("TDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSCreditCardService.ICreditCardService")]
    public interface ICreditCardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardService/ExecuteSale", ReplyAction="http://tempuri.org/ICreditCardService/ExecuteSaleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Martex.DMS.BLL.WSCreditCardService.ProcessorFaultException), Action="http://tempuri.org/ICreditCardService/ExecuteSaleProcessorFaultExceptionFault", Name="ProcessorFaultException", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
        [System.ServiceModel.FaultContractAttribute(typeof(Martex.DMS.BLL.WSCreditCardService.GenericFaultException), Action="http://tempuri.org/ICreditCardService/ExecuteSaleGenericFaultExceptionFault", Name="GenericFaultException", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
        Martex.DMS.BLL.WSCreditCardService.ProcessorResponse ExecuteSale(Martex.DMS.BLL.WSCreditCardService.SaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardService/ExecutePreAuthorization", ReplyAction="http://tempuri.org/ICreditCardService/ExecutePreAuthorizationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Martex.DMS.BLL.WSCreditCardService.GenericFaultException), Action="http://tempuri.org/ICreditCardService/ExecutePreAuthorizationGenericFaultExceptio" +
            "nFault", Name="GenericFaultException", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
        [System.ServiceModel.FaultContractAttribute(typeof(Martex.DMS.BLL.WSCreditCardService.ProcessorFaultException), Action="http://tempuri.org/ICreditCardService/ExecutePreAuthorizationProcessorFaultExcept" +
            "ionFault", Name="ProcessorFaultException", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
        Martex.DMS.BLL.WSCreditCardService.ProcessorResponse ExecutePreAuthorization(Martex.DMS.BLL.WSCreditCardService.SaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardService/ExecutePostAuthorization", ReplyAction="http://tempuri.org/ICreditCardService/ExecutePostAuthorizationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Martex.DMS.BLL.WSCreditCardService.GenericFaultException), Action="http://tempuri.org/ICreditCardService/ExecutePostAuthorizationGenericFaultExcepti" +
            "onFault", Name="GenericFaultException", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
        [System.ServiceModel.FaultContractAttribute(typeof(Martex.DMS.BLL.WSCreditCardService.ProcessorFaultException), Action="http://tempuri.org/ICreditCardService/ExecutePostAuthorizationProcessorFaultExcep" +
            "tionFault", Name="ProcessorFaultException", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
        Martex.DMS.BLL.WSCreditCardService.ProcessorResponse ExecutePostAuthorization(Martex.DMS.BLL.WSCreditCardService.PostAuthorizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardService/ExecuteForceTicket", ReplyAction="http://tempuri.org/ICreditCardService/ExecuteForceTicketResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Martex.DMS.BLL.WSCreditCardService.ProcessorFaultException), Action="http://tempuri.org/ICreditCardService/ExecuteForceTicketProcessorFaultExceptionFa" +
            "ult", Name="ProcessorFaultException", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
        [System.ServiceModel.FaultContractAttribute(typeof(Martex.DMS.BLL.WSCreditCardService.GenericFaultException), Action="http://tempuri.org/ICreditCardService/ExecuteForceTicketGenericFaultExceptionFaul" +
            "t", Name="GenericFaultException", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
        Martex.DMS.BLL.WSCreditCardService.ProcessorResponse ExecuteForceTicket(Martex.DMS.BLL.WSCreditCardService.SaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardService/ExecuteReturn", ReplyAction="http://tempuri.org/ICreditCardService/ExecuteReturnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Martex.DMS.BLL.WSCreditCardService.ProcessorFaultException), Action="http://tempuri.org/ICreditCardService/ExecuteReturnProcessorFaultExceptionFault", Name="ProcessorFaultException", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
        [System.ServiceModel.FaultContractAttribute(typeof(Martex.DMS.BLL.WSCreditCardService.GenericFaultException), Action="http://tempuri.org/ICreditCardService/ExecuteReturnGenericFaultExceptionFault", Name="GenericFaultException", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
        Martex.DMS.BLL.WSCreditCardService.ProcessorResponse ExecuteReturn(Martex.DMS.BLL.WSCreditCardService.PostAuthorizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardService/ExecuteCredit", ReplyAction="http://tempuri.org/ICreditCardService/ExecuteCreditResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Martex.DMS.BLL.WSCreditCardService.ProcessorFaultException), Action="http://tempuri.org/ICreditCardService/ExecuteCreditProcessorFaultExceptionFault", Name="ProcessorFaultException", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
        [System.ServiceModel.FaultContractAttribute(typeof(Martex.DMS.BLL.WSCreditCardService.GenericFaultException), Action="http://tempuri.org/ICreditCardService/ExecuteCreditGenericFaultExceptionFault", Name="GenericFaultException", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
        Martex.DMS.BLL.WSCreditCardService.ProcessorResponse ExecuteCredit(Martex.DMS.BLL.WSCreditCardService.SaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardService/ExecuteVoid", ReplyAction="http://tempuri.org/ICreditCardService/ExecuteVoidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Martex.DMS.BLL.WSCreditCardService.GenericFaultException), Action="http://tempuri.org/ICreditCardService/ExecuteVoidGenericFaultExceptionFault", Name="GenericFaultException", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
        [System.ServiceModel.FaultContractAttribute(typeof(Martex.DMS.BLL.WSCreditCardService.ProcessorFaultException), Action="http://tempuri.org/ICreditCardService/ExecuteVoidProcessorFaultExceptionFault", Name="ProcessorFaultException", Namespace="http://schemas.datacontract.org/2004/07/Nmca.Web.Services")]
        Martex.DMS.BLL.WSCreditCardService.ProcessorResponse ExecuteVoid(Martex.DMS.BLL.WSCreditCardService.VoidRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditCardServiceChannel : Martex.DMS.BLL.WSCreditCardService.ICreditCardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditCardServiceClient : System.ServiceModel.ClientBase<Martex.DMS.BLL.WSCreditCardService.ICreditCardService>, Martex.DMS.BLL.WSCreditCardService.ICreditCardService {
        
        public CreditCardServiceClient() {
        }
        
        public CreditCardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditCardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditCardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditCardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Martex.DMS.BLL.WSCreditCardService.ProcessorResponse ExecuteSale(Martex.DMS.BLL.WSCreditCardService.SaleRequest request) {
            return base.Channel.ExecuteSale(request);
        }
        
        public Martex.DMS.BLL.WSCreditCardService.ProcessorResponse ExecutePreAuthorization(Martex.DMS.BLL.WSCreditCardService.SaleRequest request) {
            return base.Channel.ExecutePreAuthorization(request);
        }
        
        public Martex.DMS.BLL.WSCreditCardService.ProcessorResponse ExecutePostAuthorization(Martex.DMS.BLL.WSCreditCardService.PostAuthorizationRequest request) {
            return base.Channel.ExecutePostAuthorization(request);
        }
        
        public Martex.DMS.BLL.WSCreditCardService.ProcessorResponse ExecuteForceTicket(Martex.DMS.BLL.WSCreditCardService.SaleRequest request) {
            return base.Channel.ExecuteForceTicket(request);
        }
        
        public Martex.DMS.BLL.WSCreditCardService.ProcessorResponse ExecuteReturn(Martex.DMS.BLL.WSCreditCardService.PostAuthorizationRequest request) {
            return base.Channel.ExecuteReturn(request);
        }
        
        public Martex.DMS.BLL.WSCreditCardService.ProcessorResponse ExecuteCredit(Martex.DMS.BLL.WSCreditCardService.SaleRequest request) {
            return base.Channel.ExecuteCredit(request);
        }
        
        public Martex.DMS.BLL.WSCreditCardService.ProcessorResponse ExecuteVoid(Martex.DMS.BLL.WSCreditCardService.VoidRequest request) {
            return base.Channel.ExecuteVoid(request);
        }
    }
}
