//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.BLL.PSAPNearestUS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://spectrum.pb.com/")]
    public partial class ServiceInvocationFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Output.Row", Namespace="http://www.pb.com/spectrum/services/EOLS_PSAP_Nearest_US")]
    public partial class OutputRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string distanceField;
        
        private string distanceUnitsField;
        
        private int pSAPIDField;
        
        private bool pSAPIDFieldSpecified;
        
        private int fCCIDField;
        
        private bool fCCIDFieldSpecified;
        
        private string pSAPTypeField;
        
        private string countyNameField;
        
        private string countyFIPSField;
        
        private string agencyField;
        
        private string coverageAreaField;
        
        private string coverageExceptionsField;
        
        private string coverageCommentsField;
        
        private string pSAPCommentsField;
        
        private string operatorPhoneField;
        
        private string contactPrefixField;
        
        private string contactFirstNameField;
        
        private string contactLastNameField;
        
        private string contactTitleField;
        
        private string contactPhoneField;
        
        private string contactFaxField;
        
        private string contactEmailField;
        
        private string contactCommentsField;
        
        private string mailingStreetField;
        
        private string mailingCityField;
        
        private string mailingStateField;
        
        private string mailingZipField;
        
        private string sitePhoneField;
        
        private string siteFaxField;
        
        private string siteStreetField;
        
        private string siteCityField;
        
        private string siteStateField;
        
        private string siteZipField;
        
        private string statusField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private string confidenceField;
        
        private string processedByField;
        
        private string streetDataTypeField;
        
        private string locationCodeField;
        
        private string matchCodeField;
        
        private string additionalInputDataField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string cityField;
        
        private string countryField;
        
        private string firmNameField;
        
        private string lastLineField;
        
        private string postalCodeField;
        
        private string postalCodeBaseField;
        
        private string postalCodeAddOnField;
        
        private string rRHCField;
        
        private string stateProvinceField;
        
        private string uSUrbanNameField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string streetSideField;
        
        private string inputKeyValueField;
        
        private string addressLine3Field;
        
        private string addressLine4Field;
        
        private string addressLine5Field;
        
        private string addressLine6Field;
        
        private string policePhoneField;
        
        private string firePhoneField;
        
        private string eMSPhoneField;
        
        private user_field[] user_fieldsField;
        
        /// <remarks/>
        public string Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
                this.RaisePropertyChanged("Distance");
            }
        }
        
        /// <remarks/>
        public string DistanceUnits {
            get {
                return this.distanceUnitsField;
            }
            set {
                this.distanceUnitsField = value;
                this.RaisePropertyChanged("DistanceUnits");
            }
        }
        
        /// <remarks/>
        public int PSAPID {
            get {
                return this.pSAPIDField;
            }
            set {
                this.pSAPIDField = value;
                this.RaisePropertyChanged("PSAPID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PSAPIDSpecified {
            get {
                return this.pSAPIDFieldSpecified;
            }
            set {
                this.pSAPIDFieldSpecified = value;
                this.RaisePropertyChanged("PSAPIDSpecified");
            }
        }
        
        /// <remarks/>
        public int FCCID {
            get {
                return this.fCCIDField;
            }
            set {
                this.fCCIDField = value;
                this.RaisePropertyChanged("FCCID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FCCIDSpecified {
            get {
                return this.fCCIDFieldSpecified;
            }
            set {
                this.fCCIDFieldSpecified = value;
                this.RaisePropertyChanged("FCCIDSpecified");
            }
        }
        
        /// <remarks/>
        public string PSAPType {
            get {
                return this.pSAPTypeField;
            }
            set {
                this.pSAPTypeField = value;
                this.RaisePropertyChanged("PSAPType");
            }
        }
        
        /// <remarks/>
        public string CountyName {
            get {
                return this.countyNameField;
            }
            set {
                this.countyNameField = value;
                this.RaisePropertyChanged("CountyName");
            }
        }
        
        /// <remarks/>
        public string CountyFIPS {
            get {
                return this.countyFIPSField;
            }
            set {
                this.countyFIPSField = value;
                this.RaisePropertyChanged("CountyFIPS");
            }
        }
        
        /// <remarks/>
        public string Agency {
            get {
                return this.agencyField;
            }
            set {
                this.agencyField = value;
                this.RaisePropertyChanged("Agency");
            }
        }
        
        /// <remarks/>
        public string CoverageArea {
            get {
                return this.coverageAreaField;
            }
            set {
                this.coverageAreaField = value;
                this.RaisePropertyChanged("CoverageArea");
            }
        }
        
        /// <remarks/>
        public string CoverageExceptions {
            get {
                return this.coverageExceptionsField;
            }
            set {
                this.coverageExceptionsField = value;
                this.RaisePropertyChanged("CoverageExceptions");
            }
        }
        
        /// <remarks/>
        public string CoverageComments {
            get {
                return this.coverageCommentsField;
            }
            set {
                this.coverageCommentsField = value;
                this.RaisePropertyChanged("CoverageComments");
            }
        }
        
        /// <remarks/>
        public string PSAPComments {
            get {
                return this.pSAPCommentsField;
            }
            set {
                this.pSAPCommentsField = value;
                this.RaisePropertyChanged("PSAPComments");
            }
        }
        
        /// <remarks/>
        public string OperatorPhone {
            get {
                return this.operatorPhoneField;
            }
            set {
                this.operatorPhoneField = value;
                this.RaisePropertyChanged("OperatorPhone");
            }
        }
        
        /// <remarks/>
        public string ContactPrefix {
            get {
                return this.contactPrefixField;
            }
            set {
                this.contactPrefixField = value;
                this.RaisePropertyChanged("ContactPrefix");
            }
        }
        
        /// <remarks/>
        public string ContactFirstName {
            get {
                return this.contactFirstNameField;
            }
            set {
                this.contactFirstNameField = value;
                this.RaisePropertyChanged("ContactFirstName");
            }
        }
        
        /// <remarks/>
        public string ContactLastName {
            get {
                return this.contactLastNameField;
            }
            set {
                this.contactLastNameField = value;
                this.RaisePropertyChanged("ContactLastName");
            }
        }
        
        /// <remarks/>
        public string ContactTitle {
            get {
                return this.contactTitleField;
            }
            set {
                this.contactTitleField = value;
                this.RaisePropertyChanged("ContactTitle");
            }
        }
        
        /// <remarks/>
        public string ContactPhone {
            get {
                return this.contactPhoneField;
            }
            set {
                this.contactPhoneField = value;
                this.RaisePropertyChanged("ContactPhone");
            }
        }
        
        /// <remarks/>
        public string ContactFax {
            get {
                return this.contactFaxField;
            }
            set {
                this.contactFaxField = value;
                this.RaisePropertyChanged("ContactFax");
            }
        }
        
        /// <remarks/>
        public string ContactEmail {
            get {
                return this.contactEmailField;
            }
            set {
                this.contactEmailField = value;
                this.RaisePropertyChanged("ContactEmail");
            }
        }
        
        /// <remarks/>
        public string ContactComments {
            get {
                return this.contactCommentsField;
            }
            set {
                this.contactCommentsField = value;
                this.RaisePropertyChanged("ContactComments");
            }
        }
        
        /// <remarks/>
        public string MailingStreet {
            get {
                return this.mailingStreetField;
            }
            set {
                this.mailingStreetField = value;
                this.RaisePropertyChanged("MailingStreet");
            }
        }
        
        /// <remarks/>
        public string MailingCity {
            get {
                return this.mailingCityField;
            }
            set {
                this.mailingCityField = value;
                this.RaisePropertyChanged("MailingCity");
            }
        }
        
        /// <remarks/>
        public string MailingState {
            get {
                return this.mailingStateField;
            }
            set {
                this.mailingStateField = value;
                this.RaisePropertyChanged("MailingState");
            }
        }
        
        /// <remarks/>
        public string MailingZip {
            get {
                return this.mailingZipField;
            }
            set {
                this.mailingZipField = value;
                this.RaisePropertyChanged("MailingZip");
            }
        }
        
        /// <remarks/>
        public string SitePhone {
            get {
                return this.sitePhoneField;
            }
            set {
                this.sitePhoneField = value;
                this.RaisePropertyChanged("SitePhone");
            }
        }
        
        /// <remarks/>
        public string SiteFax {
            get {
                return this.siteFaxField;
            }
            set {
                this.siteFaxField = value;
                this.RaisePropertyChanged("SiteFax");
            }
        }
        
        /// <remarks/>
        public string SiteStreet {
            get {
                return this.siteStreetField;
            }
            set {
                this.siteStreetField = value;
                this.RaisePropertyChanged("SiteStreet");
            }
        }
        
        /// <remarks/>
        public string SiteCity {
            get {
                return this.siteCityField;
            }
            set {
                this.siteCityField = value;
                this.RaisePropertyChanged("SiteCity");
            }
        }
        
        /// <remarks/>
        public string SiteState {
            get {
                return this.siteStateField;
            }
            set {
                this.siteStateField = value;
                this.RaisePropertyChanged("SiteState");
            }
        }
        
        /// <remarks/>
        public string SiteZip {
            get {
                return this.siteZipField;
            }
            set {
                this.siteZipField = value;
                this.RaisePropertyChanged("SiteZip");
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Status.Code")]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Status.Description")]
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
                this.RaisePropertyChanged("StatusDescription");
            }
        }
        
        /// <remarks/>
        public string Confidence {
            get {
                return this.confidenceField;
            }
            set {
                this.confidenceField = value;
                this.RaisePropertyChanged("Confidence");
            }
        }
        
        /// <remarks/>
        public string ProcessedBy {
            get {
                return this.processedByField;
            }
            set {
                this.processedByField = value;
                this.RaisePropertyChanged("ProcessedBy");
            }
        }
        
        /// <remarks/>
        public string StreetDataType {
            get {
                return this.streetDataTypeField;
            }
            set {
                this.streetDataTypeField = value;
                this.RaisePropertyChanged("StreetDataType");
            }
        }
        
        /// <remarks/>
        public string LocationCode {
            get {
                return this.locationCodeField;
            }
            set {
                this.locationCodeField = value;
                this.RaisePropertyChanged("LocationCode");
            }
        }
        
        /// <remarks/>
        public string MatchCode {
            get {
                return this.matchCodeField;
            }
            set {
                this.matchCodeField = value;
                this.RaisePropertyChanged("MatchCode");
            }
        }
        
        /// <remarks/>
        public string AdditionalInputData {
            get {
                return this.additionalInputDataField;
            }
            set {
                this.additionalInputDataField = value;
                this.RaisePropertyChanged("AdditionalInputData");
            }
        }
        
        /// <remarks/>
        public string AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
                this.RaisePropertyChanged("AddressLine1");
            }
        }
        
        /// <remarks/>
        public string AddressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
                this.RaisePropertyChanged("AddressLine2");
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        public string FirmName {
            get {
                return this.firmNameField;
            }
            set {
                this.firmNameField = value;
                this.RaisePropertyChanged("FirmName");
            }
        }
        
        /// <remarks/>
        public string LastLine {
            get {
                return this.lastLineField;
            }
            set {
                this.lastLineField = value;
                this.RaisePropertyChanged("LastLine");
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PostalCode.Base")]
        public string PostalCodeBase {
            get {
                return this.postalCodeBaseField;
            }
            set {
                this.postalCodeBaseField = value;
                this.RaisePropertyChanged("PostalCodeBase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PostalCode.AddOn")]
        public string PostalCodeAddOn {
            get {
                return this.postalCodeAddOnField;
            }
            set {
                this.postalCodeAddOnField = value;
                this.RaisePropertyChanged("PostalCodeAddOn");
            }
        }
        
        /// <remarks/>
        public string RRHC {
            get {
                return this.rRHCField;
            }
            set {
                this.rRHCField = value;
                this.RaisePropertyChanged("RRHC");
            }
        }
        
        /// <remarks/>
        public string StateProvince {
            get {
                return this.stateProvinceField;
            }
            set {
                this.stateProvinceField = value;
                this.RaisePropertyChanged("StateProvince");
            }
        }
        
        /// <remarks/>
        public string USUrbanName {
            get {
                return this.uSUrbanNameField;
            }
            set {
                this.uSUrbanNameField = value;
                this.RaisePropertyChanged("USUrbanName");
            }
        }
        
        /// <remarks/>
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        public string StreetSide {
            get {
                return this.streetSideField;
            }
            set {
                this.streetSideField = value;
                this.RaisePropertyChanged("StreetSide");
            }
        }
        
        /// <remarks/>
        public string InputKeyValue {
            get {
                return this.inputKeyValueField;
            }
            set {
                this.inputKeyValueField = value;
                this.RaisePropertyChanged("InputKeyValue");
            }
        }
        
        /// <remarks/>
        public string AddressLine3 {
            get {
                return this.addressLine3Field;
            }
            set {
                this.addressLine3Field = value;
                this.RaisePropertyChanged("AddressLine3");
            }
        }
        
        /// <remarks/>
        public string AddressLine4 {
            get {
                return this.addressLine4Field;
            }
            set {
                this.addressLine4Field = value;
                this.RaisePropertyChanged("AddressLine4");
            }
        }
        
        /// <remarks/>
        public string AddressLine5 {
            get {
                return this.addressLine5Field;
            }
            set {
                this.addressLine5Field = value;
                this.RaisePropertyChanged("AddressLine5");
            }
        }
        
        /// <remarks/>
        public string AddressLine6 {
            get {
                return this.addressLine6Field;
            }
            set {
                this.addressLine6Field = value;
                this.RaisePropertyChanged("AddressLine6");
            }
        }
        
        /// <remarks/>
        public string PolicePhone {
            get {
                return this.policePhoneField;
            }
            set {
                this.policePhoneField = value;
                this.RaisePropertyChanged("PolicePhone");
            }
        }
        
        /// <remarks/>
        public string FirePhone {
            get {
                return this.firePhoneField;
            }
            set {
                this.firePhoneField = value;
                this.RaisePropertyChanged("FirePhone");
            }
        }
        
        /// <remarks/>
        public string EMSPhone {
            get {
                return this.eMSPhoneField;
            }
            set {
                this.eMSPhoneField = value;
                this.RaisePropertyChanged("EMSPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public user_field[] user_fields {
            get {
                return this.user_fieldsField;
            }
            set {
                this.user_fieldsField = value;
                this.RaisePropertyChanged("user_fields");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pb.com/spectrum/services/EOLS_PSAP_Nearest_US")]
    public partial class user_field : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Input.Row", Namespace="http://www.pb.com/spectrum/services/EOLS_PSAP_Nearest_US")]
    public partial class InputRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string inputKeyValueField;
        
        private string firmNameField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string addressLine3Field;
        
        private string addressLine4Field;
        
        private string addressLine5Field;
        
        private string addressLine6Field;
        
        private string lastLineField;
        
        private string cityField;
        
        private string stateProvinceField;
        
        private string postalCodeField;
        
        private user_field[] user_fieldsField;
        
        /// <remarks/>
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        public string InputKeyValue {
            get {
                return this.inputKeyValueField;
            }
            set {
                this.inputKeyValueField = value;
                this.RaisePropertyChanged("InputKeyValue");
            }
        }
        
        /// <remarks/>
        public string FirmName {
            get {
                return this.firmNameField;
            }
            set {
                this.firmNameField = value;
                this.RaisePropertyChanged("FirmName");
            }
        }
        
        /// <remarks/>
        public string AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
                this.RaisePropertyChanged("AddressLine1");
            }
        }
        
        /// <remarks/>
        public string AddressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
                this.RaisePropertyChanged("AddressLine2");
            }
        }
        
        /// <remarks/>
        public string AddressLine3 {
            get {
                return this.addressLine3Field;
            }
            set {
                this.addressLine3Field = value;
                this.RaisePropertyChanged("AddressLine3");
            }
        }
        
        /// <remarks/>
        public string AddressLine4 {
            get {
                return this.addressLine4Field;
            }
            set {
                this.addressLine4Field = value;
                this.RaisePropertyChanged("AddressLine4");
            }
        }
        
        /// <remarks/>
        public string AddressLine5 {
            get {
                return this.addressLine5Field;
            }
            set {
                this.addressLine5Field = value;
                this.RaisePropertyChanged("AddressLine5");
            }
        }
        
        /// <remarks/>
        public string AddressLine6 {
            get {
                return this.addressLine6Field;
            }
            set {
                this.addressLine6Field = value;
                this.RaisePropertyChanged("AddressLine6");
            }
        }
        
        /// <remarks/>
        public string LastLine {
            get {
                return this.lastLineField;
            }
            set {
                this.lastLineField = value;
                this.RaisePropertyChanged("LastLine");
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        public string StateProvince {
            get {
                return this.stateProvinceField;
            }
            set {
                this.stateProvinceField = value;
                this.RaisePropertyChanged("StateProvince");
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public user_field[] user_fields {
            get {
                return this.user_fieldsField;
            }
            set {
                this.user_fieldsField = value;
                this.RaisePropertyChanged("user_fields");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pb.com/spectrum/services/EOLS_PSAP_Nearest_US")]
    public partial class options : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maxDistanceField;
        
        private string maxCandidatesField;
        
        private DistanceUnits distanceUnitsField;
        
        private bool distanceUnitsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MaxDistance {
            get {
                return this.maxDistanceField;
            }
            set {
                this.maxDistanceField = value;
                this.RaisePropertyChanged("MaxDistance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MaxCandidates {
            get {
                return this.maxCandidatesField;
            }
            set {
                this.maxCandidatesField = value;
                this.RaisePropertyChanged("MaxCandidates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DistanceUnits DistanceUnits {
            get {
                return this.distanceUnitsField;
            }
            set {
                this.distanceUnitsField = value;
                this.RaisePropertyChanged("DistanceUnits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceUnitsSpecified {
            get {
                return this.distanceUnitsFieldSpecified;
            }
            set {
                this.distanceUnitsFieldSpecified = value;
                this.RaisePropertyChanged("DistanceUnitsSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pb.com/spectrum/services/EOLS_PSAP_Nearest_US")]
    public enum DistanceUnits {
        
        /// <remarks/>
        Feet,
        
        /// <remarks/>
        Yards,
        
        /// <remarks/>
        Miles,
        
        /// <remarks/>
        Meters,
        
        /// <remarks/>
        Kilometers,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://spectrum.pb.com/", ConfigurationName="PSAPNearestUS.EOLS_PSAP_Nearest_US")]
    public interface EOLS_PSAP_Nearest_US {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.pb.com/spectrum/services/EOLS_PSAP_Nearest_US) of message EOLS_PSAP_Nearest_US does not match the default value (http://spectrum.pb.com/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Martex.DMS.BLL.PSAPNearestUS.ServiceInvocationFault), Action="", Name="ServiceInvocationFault", Namespace="http://www.pb.com/spectrum/services/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(user_field[]))]
        Martex.DMS.BLL.PSAPNearestUS.EOLS_PSAP_Nearest_USResponse EOLS_PSAP_Nearest_US(Martex.DMS.BLL.PSAPNearestUS.EOLS_PSAP_Nearest_US1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EOLS_PSAP_Nearest_USRequest", WrapperNamespace="http://www.pb.com/spectrum/services/EOLS_PSAP_Nearest_US", IsWrapped=true)]
    public partial class EOLS_PSAP_Nearest_US1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.pb.com/spectrum/services/EOLS_PSAP_Nearest_US", Order=0)]
        public Martex.DMS.BLL.PSAPNearestUS.options options;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.pb.com/spectrum/services/EOLS_PSAP_Nearest_US", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Row", IsNullable=false)]
        public Martex.DMS.BLL.PSAPNearestUS.InputRow[] Input;
        
        public EOLS_PSAP_Nearest_US1() {
        }
        
        public EOLS_PSAP_Nearest_US1(Martex.DMS.BLL.PSAPNearestUS.options options, Martex.DMS.BLL.PSAPNearestUS.InputRow[] Input) {
            this.options = options;
            this.Input = Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EOLS_PSAP_Nearest_USResponse", WrapperNamespace="http://www.pb.com/spectrum/services/EOLS_PSAP_Nearest_US", IsWrapped=true)]
    public partial class EOLS_PSAP_Nearest_USResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.pb.com/spectrum/services/EOLS_PSAP_Nearest_US", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Row", IsNullable=false)]
        public Martex.DMS.BLL.PSAPNearestUS.OutputRow[] Output;
        
        public EOLS_PSAP_Nearest_USResponse() {
        }
        
        public EOLS_PSAP_Nearest_USResponse(Martex.DMS.BLL.PSAPNearestUS.OutputRow[] Output) {
            this.Output = Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EOLS_PSAP_Nearest_USChannel : Martex.DMS.BLL.PSAPNearestUS.EOLS_PSAP_Nearest_US, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EOLS_PSAP_Nearest_USClient : System.ServiceModel.ClientBase<Martex.DMS.BLL.PSAPNearestUS.EOLS_PSAP_Nearest_US>, Martex.DMS.BLL.PSAPNearestUS.EOLS_PSAP_Nearest_US {
        
        public EOLS_PSAP_Nearest_USClient() {
        }
        
        public EOLS_PSAP_Nearest_USClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EOLS_PSAP_Nearest_USClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EOLS_PSAP_Nearest_USClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EOLS_PSAP_Nearest_USClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Martex.DMS.BLL.PSAPNearestUS.EOLS_PSAP_Nearest_USResponse Martex.DMS.BLL.PSAPNearestUS.EOLS_PSAP_Nearest_US.EOLS_PSAP_Nearest_US(Martex.DMS.BLL.PSAPNearestUS.EOLS_PSAP_Nearest_US1 request) {
            return base.Channel.EOLS_PSAP_Nearest_US(request);
        }
        
        public Martex.DMS.BLL.PSAPNearestUS.OutputRow[] EOLS_PSAP_Nearest_US(Martex.DMS.BLL.PSAPNearestUS.options options, Martex.DMS.BLL.PSAPNearestUS.InputRow[] Input) {
            Martex.DMS.BLL.PSAPNearestUS.EOLS_PSAP_Nearest_US1 inValue = new Martex.DMS.BLL.PSAPNearestUS.EOLS_PSAP_Nearest_US1();
            inValue.options = options;
            inValue.Input = Input;
            Martex.DMS.BLL.PSAPNearestUS.EOLS_PSAP_Nearest_USResponse retVal = ((Martex.DMS.BLL.PSAPNearestUS.EOLS_PSAP_Nearest_US)(this)).EOLS_PSAP_Nearest_US(inValue);
            return retVal.Output;
        }
    }
}
