//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class ApplicationConfiguration
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationConfigurationTypeID { get; set; }
        public Nullable<int> ApplicationConfigurationCategoryID { get; set; }
        public Nullable<int> ControlTypeID { get; set; }
        public Nullable<int> DataTypeID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    
        public virtual ApplicationConfigurationType ApplicationConfigurationType { get; set; }
        public virtual ApplicationConfigurationCategory ApplicationConfigurationCategory { get; set; }
        public virtual ControlType ControlType { get; set; }
        public virtual DataType DataType { get; set; }
    }
}
