//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class BillingDefinitionInvoice
    {
    	public BillingDefinitionInvoice()
        {
            this.BillingDefinitionInvoiceLines = new HashSet<BillingDefinitionInvoiceLine>();
            this.BillingInvoices = new HashSet<BillingInvoice>();
            this.BillingInvoiceDetails = new HashSet<BillingInvoiceDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ScheduleTypeID { get; set; }
        public Nullable<int> ScheduleDateTypeID { get; set; }
        public Nullable<int> ScheduleRangeTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string AccountingSystemCustomerNumber { get; set; }
        public string AccountingSystemAddressCode { get; set; }
        public string POPrefix { get; set; }
        public string PONumber { get; set; }
        public Nullable<int> InvoiceTypeID { get; set; }
        public Nullable<int> InvoiceTemplateID { get; set; }
        public Nullable<int> DefaultInvoiceStatusID { get; set; }
        public Nullable<bool> CanAddLines { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual BillingInvoiceStatu BillingInvoiceStatu { get; set; }
        public virtual BillingInvoiceTemplate BillingInvoiceTemplate { get; set; }
        public virtual BillingInvoiceType BillingInvoiceType { get; set; }
        public virtual BillingScheduleDateType BillingScheduleDateType { get; set; }
        public virtual BillingScheduleRangeType BillingScheduleRangeType { get; set; }
        public virtual BillingScheduleType BillingScheduleType { get; set; }
        public virtual ICollection<BillingDefinitionInvoiceLine> BillingDefinitionInvoiceLines { get; set; }
        public virtual ICollection<BillingInvoice> BillingInvoices { get; set; }
        public virtual ICollection<BillingInvoiceDetail> BillingInvoiceDetails { get; set; }
    }
}
