//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class BillingDefinitionInvoiceLineEvent
    {
    	public BillingDefinitionInvoiceLineEvent()
        {
            this.BillingDefinitionInvoiceLineEventPrograms = new HashSet<BillingDefinitionInvoiceLineEventProgram>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BillingDefinitionInvoiceLineID { get; set; }
        public Nullable<int> BillingDefinitionEventID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string EventFilter { get; set; }
        public Nullable<bool> IsAdjustable { get; set; }
        public Nullable<bool> IsExcludable { get; set; }
        public Nullable<int> DefaultInvoiceDetailStatusID { get; set; }
        public Nullable<int> EventGenWhenID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<bool> IsEditable { get; set; }
    
        public virtual BillingDefinitionEvent BillingDefinitionEvent { get; set; }
        public virtual BillingDefinitionInvoiceLine BillingDefinitionInvoiceLine { get; set; }
        public virtual BillingInvoiceDetailStatu BillingInvoiceDetailStatu { get; set; }
        public virtual ICollection<BillingDefinitionInvoiceLineEventProgram> BillingDefinitionInvoiceLineEventPrograms { get; set; }
    }
}
