//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class BillingInvoiceDetailException
    {
        public int ID { get; set; }
        public Nullable<int> BillingInvoiceDetailID { get; set; }
        public Nullable<int> InvoiceDetailExceptionTypeID { get; set; }
        public Nullable<int> InvoiceDetailExceptionStatusID { get; set; }
        public Nullable<int> InvoiceDetailExceptionSeverityID { get; set; }
        public string InvoiceDetailExceptionComment { get; set; }
        public string ExceptionAuthorization { get; set; }
        public Nullable<System.DateTime> ExceptionAuthorizationDate { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    
        public virtual BillingInvoiceDetail BillingInvoiceDetail { get; set; }
        public virtual BillingInvoiceDetailExceptionSeverity BillingInvoiceDetailExceptionSeverity { get; set; }
        public virtual BillingInvoiceDetailExceptionStatu BillingInvoiceDetailExceptionStatu { get; set; }
        public virtual BillingInvoiceDetailExceptionType BillingInvoiceDetailExceptionType { get; set; }
    }
}
