//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class BillingInvoiceLine
    {
        public int ID { get; set; }
        public Nullable<int> BillingInvoiceID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> RateTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public string AccountingSystemGLCode { get; set; }
        public Nullable<int> LineQuantity { get; set; }
        public Nullable<decimal> LineCost { get; set; }
        public Nullable<decimal> LineAmount { get; set; }
        public Nullable<int> InvoiceLineStatusID { get; set; }
        public Nullable<int> BillingDefinitionInvoiceLineID { get; set; }
        public string AccountingSystemItemCode { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    
        public virtual BillingDefinitionInvoiceLine BillingDefinitionInvoiceLine { get; set; }
        public virtual BillingInvoice BillingInvoice { get; set; }
        public virtual BillingInvoiceLineStatu BillingInvoiceLineStatu { get; set; }
        public virtual RateType RateType { get; set; }
        public virtual Product Product { get; set; }
    }
}
