//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class BillingDefinitionInvoiceLine
    {
    	public BillingDefinitionInvoiceLine()
        {
            this.BillingDefinitionInvoiceLineEvents = new HashSet<BillingDefinitionInvoiceLineEvent>();
            this.BillingInvoiceDetails = new HashSet<BillingInvoiceDetail>();
            this.BillingInvoiceLines = new HashSet<BillingInvoiceLine>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BillingDefinitionInvoiceID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> RateTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> FixedQuantity { get; set; }
        public Nullable<int> DefaultInvoiceLineStatusID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    
        public virtual BillingDefinitionInvoice BillingDefinitionInvoice { get; set; }
        public virtual BillingInvoiceLineStatu BillingInvoiceLineStatu { get; set; }
        public virtual RateType RateType { get; set; }
        public virtual ICollection<BillingDefinitionInvoiceLineEvent> BillingDefinitionInvoiceLineEvents { get; set; }
        public virtual ICollection<BillingInvoiceDetail> BillingInvoiceDetails { get; set; }
        public virtual ICollection<BillingInvoiceLine> BillingInvoiceLines { get; set; }
        public virtual Product Product { get; set; }
    }
}
