//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class CasePhoneLocation
    {
        public int ID { get; set; }
        public Nullable<int> CaseID { get; set; }
        public Nullable<int> InboundCallID { get; set; }
        public Nullable<int> PhoneTypeID { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> LocationDate { get; set; }
        public Nullable<bool> IsSMSAvailable { get; set; }
        public string LocationAccuracy { get; set; }
        public Nullable<int> GeoAccuracy { get; set; }
        public Nullable<decimal> CivicLatitude { get; set; }
        public Nullable<decimal> CivicLongitude { get; set; }
        public Nullable<int> CivicDistance { get; set; }
        public string CivicDirection { get; set; }
        public string CivicStreet { get; set; }
        public string CivicCity { get; set; }
        public string CivicCounty { get; set; }
        public string CivicState { get; set; }
        public string CivicZip { get; set; }
        public string CivicCountry { get; set; }
        public Nullable<decimal> CrossLatitude { get; set; }
        public Nullable<decimal> CrossLongitude { get; set; }
        public Nullable<int> CrossDistance { get; set; }
        public string CrossDirection { get; set; }
        public string CrossStreet { get; set; }
        public Nullable<decimal> IntersectionLatitude { get; set; }
        public Nullable<decimal> IntersectionLongitude { get; set; }
        public Nullable<int> IntersectionDistance { get; set; }
        public string IntersectionDirection { get; set; }
        public string IntersectionStreet1 { get; set; }
        public string IntersectionStreet2 { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual PhoneType PhoneType { get; set; }
        public virtual InboundCall InboundCall { get; set; }
    }
}
