//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class ClaimVehicleDiagnosticCode
    {
        public int ID { get; set; }
        public Nullable<int> ClaimID { get; set; }
        public Nullable<int> VehicleDiagnosticCodeID { get; set; }
        public string VehicleDiagnosticCodeType { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
    
        public virtual Claim Claim { get; set; }
        public virtual VehicleDiagnosticCode VehicleDiagnosticCode { get; set; }
    }
}
