//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class ClaimTypeCategory
    {
        public int ID { get; set; }
        public int ClaimTypeID { get; set; }
        public int ClaimCategoryID { get; set; }
    
        public virtual ClaimCategory ClaimCategory { get; set; }
        public virtual ClaimType ClaimType { get; set; }
    }
}
