//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class Claim
    {
    	public Claim()
        {
            this.ClaimStatusLogs = new HashSet<ClaimStatusLog>();
            this.ClaimVehicleDiagnosticCodes = new HashSet<ClaimVehicleDiagnosticCode>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ClaimTypeID { get; set; }
        public Nullable<int> ClaimCategoryID { get; set; }
        public Nullable<int> ClaimStatusID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public Nullable<System.DateTime> ClaimDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<int> ReceiveContactMethodID { get; set; }
        public string ClaimDescription { get; set; }
        public string ContactName { get; set; }
        public string ContactPhoneNumber { get; set; }
        public string ContactEmailAddress { get; set; }
        public string PaymentAddressLine1 { get; set; }
        public string PaymentAddressLine2 { get; set; }
        public string PaymentAddressLine3 { get; set; }
        public string PaymentAddressCity { get; set; }
        public string PaymentAddressStateProvince { get; set; }
        public string PaymentAddressPostalCode { get; set; }
        public string PaymentAddressCountryCode { get; set; }
        public Nullable<int> PaymentAddressCountryID { get; set; }
        public Nullable<int> PaymentAddressStateProvinceID { get; set; }
        public Nullable<int> ServiceProductCategoryID { get; set; }
        public string ServiceLocation { get; set; }
        public string DestinationLocation { get; set; }
        public string ServiceFacilityName { get; set; }
        public string ServiceFacilityPACode { get; set; }
        public Nullable<decimal> ServiceMiles { get; set; }
        public Nullable<bool> IsServiceReceiptOnFile { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public Nullable<int> VehicleCategoryID { get; set; }
        public Nullable<int> RVTypeID { get; set; }
        public string VehicleVIN { get; set; }
        public string VehicleYear { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleMakeOther { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleModelOther { get; set; }
        public string VehicleChassis { get; set; }
        public string VehicleEngine { get; set; }
        public string VehicleTransmission { get; set; }
        public Nullable<System.DateTime> WarrantyStartDate { get; set; }
        public Nullable<int> WarrantyYears { get; set; }
        public Nullable<int> WarrantyMiles { get; set; }
        public Nullable<int> CurrentMiles { get; set; }
        public Nullable<int> NextActionID { get; set; }
        public Nullable<int> NextActionAssignedToUserID { get; set; }
        public Nullable<System.DateTime> NextActionScheduledDate { get; set; }
        public Nullable<decimal> AmountRequested { get; set; }
        public Nullable<decimal> AmountApproved { get; set; }
        public Nullable<System.DateTime> ClaimDecisionDate { get; set; }
        public string ClaimDecisionBy { get; set; }
        public Nullable<int> ClaimRejectReasonID { get; set; }
        public string ClaimRejectReasonOther { get; set; }
        public string GWOApprovalCode { get; set; }
        public string CUDLCaseNumber { get; set; }
        public string ACESReferenceNumber { get; set; }
        public Nullable<System.DateTime> ACESSubmitDate { get; set; }
        public string ACESOutcome { get; set; }
        public Nullable<System.DateTime> ACESClearedDate { get; set; }
        public Nullable<int> ClientPaymentID { get; set; }
        public Nullable<decimal> ACESAmount { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public Nullable<int> ExportBatchID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string PaymentPayeeName { get; set; }
        public string CheckNumber { get; set; }
        public Nullable<System.DateTime> CheckClearedDate { get; set; }
        public Nullable<int> SourceSystemID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string PayeeType { get; set; }
        public Nullable<int> PassthruAccountingInvoiceBatchID { get; set; }
        public Nullable<int> FeeAccountingInvoiceBatchID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public string VehicleOwnerName { get; set; }
        public Nullable<bool> IsFirstOwner { get; set; }
        public Nullable<int> ACESClaimStatusID { get; set; }
        public Nullable<decimal> ACESFeeAmount { get; set; }
    
        public virtual ACESClaimStatu ACESClaimStatu { get; set; }
        public virtual ClaimCategory ClaimCategory { get; set; }
        public virtual ClaimRejectReason ClaimRejectReason { get; set; }
        public virtual ClaimStatu ClaimStatu { get; set; }
        public virtual ClaimType ClaimType { get; set; }
        public virtual ClientPayment ClientPayment { get; set; }
        public virtual NextAction NextAction { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Program Program { get; set; }
        public virtual RVType RVType { get; set; }
        public virtual SourceSystem SourceSystem { get; set; }
        public virtual VehicleCategory VehicleCategory { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<ClaimStatusLog> ClaimStatusLogs { get; set; }
        public virtual ICollection<ClaimVehicleDiagnosticCode> ClaimVehicleDiagnosticCodes { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual Member Member { get; set; }
        public virtual Batch Batch { get; set; }
        public virtual Country Country { get; set; }
        public virtual StateProvince StateProvince { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
