//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class CoachingConcern
    {
        public int ID { get; set; }
        public Nullable<int> ConcernTypeID { get; set; }
        public Nullable<int> ConcernID { get; set; }
        public string AgentUserName { get; set; }
        public string TeamManager { get; set; }
        public Nullable<int> CallRecordingID { get; set; }
        public Nullable<int> ServiceRequestID { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsAppealed { get; set; }
        public Nullable<System.DateTime> AppealedDate { get; set; }
        public Nullable<bool> IsInternalAppeal { get; set; }
        public Nullable<System.DateTime> InternalAppealDate { get; set; }
        public Nullable<bool> AppealApproved { get; set; }
        public Nullable<bool> IsCoached { get; set; }
        public Nullable<System.DateTime> CoachedDate { get; set; }
        public Nullable<System.DateTime> PendingDate { get; set; }
        public Nullable<bool> SevereQualityViolation { get; set; }
        public Nullable<bool> ZeroToleranceViolation { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    
        public virtual Concern Concern { get; set; }
        public virtual ConcernType ConcernType { get; set; }
    }
}
