//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class CommunicationQueue
    {
        public int ID { get; set; }
        public Nullable<int> ContactLogID { get; set; }
        public Nullable<int> ContactMethodID { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public string MessageData { get; set; }
        public string Subject { get; set; }
        public string MessageText { get; set; }
        public Nullable<int> Attempts { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string NotificationRecipient { get; set; }
        public Nullable<long> EventLogID { get; set; }
        public string QueueARN { get; set; }
        public int? ServiceRequestID { get; set; }

        public virtual ContactMethod ContactMethod { get; set; }
        public virtual ContactLog ContactLog { get; set; }
    }
}
