//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class Concern
    {
    	public Concern()
        {
            this.CoachingConcerns = new HashSet<CoachingConcern>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ConcernTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<CoachingConcern> CoachingConcerns { get; set; }
        public virtual ConcernType ConcernType { get; set; }
    }
}
