//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class ContactLogConnectData
    {
    	public ContactLogConnectData()
        {
            this.ContactLogs = new HashSet<ContactLog>();
        }
    
        public int ID { get; set; }
        public string ConnectContactID { get; set; }
        public string AgentUsername { get; set; }
        public string CustomerEndpoint { get; set; }
        public string SystemEndpoint { get; set; }
        public Nullable<int> CustomerHoldDuration { get; set; }
        public Nullable<int> LongestCustomerHoldDuration { get; set; }
        public Nullable<int> AfterContactWorkDuration { get; set; }
        public Nullable<int> AgentIntractionDuration { get; set; }
        public string QueueName { get; set; }
        public Nullable<int> QueueDuration { get; set; }
        public string RecordingLocation { get; set; }
        public string CTRRecord { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string InitialContactID { get; set; }
        public string NextContactId { get; set; }
        public string PreviousContactID { get; set; }
        public string CustomerEndpointType { get; set; }
        public string InitiationMethod { get; set; }
        public Nullable<System.DateTime> InitiationTimestamp { get; set; }
        public string QueueARN { get; set; }
        public Nullable<System.DateTime> EnqueueTimestamp { get; set; }
        public Nullable<System.DateTime> DequeueTimestamp { get; set; }
        public string AgentARN { get; set; }
        public string AgentRoutingProfileARN { get; set; }
        public string AgentRoutingProfileName { get; set; }
        public Nullable<int> AgentNumberOfHolds { get; set; }
        public Nullable<System.DateTime> ConnectedToAgentTimestamp { get; set; }
        public Nullable<System.DateTime> TransferCompletedTimestamp { get; set; }
        public string TransferredToEndpoint { get; set; }
        public Nullable<System.DateTime> AfterContactWorkStartTimestamp { get; set; }
        public Nullable<System.DateTime> AfterContactWorkEndTimestamp { get; set; }
        public string Channel { get; set; }
        public Nullable<System.DateTime> ConnectedToSystemTimestamp { get; set; }
        public Nullable<System.DateTime> DisconnectTimestamp { get; set; }
        public string RecordingStatus { get; set; }
        public string RecordingType { get; set; }
        public string RecordingDeletionReason { get; set; }
        public string AWSAccount { get; set; }
        public string InstanceARN { get; set; }
    
        public virtual ICollection<ContactLog> ContactLogs { get; set; }
    }
}
