//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class ContactCategory
    {
    	public ContactCategory()
        {
            this.CallTypes = new HashSet<CallType>();
            this.ContactActions = new HashSet<ContactAction>();
            this.ContactLogs = new HashSet<ContactLog>();
            this.ContactReasons = new HashSet<ContactReason>();
            this.ContactSources = new HashSet<ContactSource>();
            this.NextActions = new HashSet<NextAction>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsShownOnFinish { get; set; }
        public Nullable<bool> IsShownOnActivity { get; set; }
    
        public virtual ICollection<CallType> CallTypes { get; set; }
        public virtual ICollection<ContactAction> ContactActions { get; set; }
        public virtual ICollection<ContactLog> ContactLogs { get; set; }
        public virtual ICollection<ContactReason> ContactReasons { get; set; }
        public virtual ICollection<ContactSource> ContactSources { get; set; }
        public virtual ICollection<NextAction> NextActions { get; set; }
    }
}
