//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class ContractRateScheduleProductLog
    {
        public int ID { get; set; }
        public int ContractRateScheduleID { get; set; }
        public Nullable<int> VendorLocationID { get; set; }
        public int ProductID { get; set; }
        public int RateTypeID { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
        public Nullable<int> OldQuantity { get; set; }
        public Nullable<int> NewQuantity { get; set; }
        public string ActivityType { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
    
        public virtual ContractRateSchedule ContractRateSchedule { get; set; }
        public virtual RateType RateType { get; set; }
        public virtual VendorLocation VendorLocation { get; set; }
        public virtual Product Product { get; set; }
    }
}
