//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class ContactAction
    {
    	public ContactAction()
        {
            this.ContactLogActions = new HashSet<ContactLogAction>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ContactCategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsShownOnScreen { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsTalkedToRequired { get; set; }
        public Nullable<decimal> VendorServiceRatingAdjustment { get; set; }
    
        public virtual ICollection<ContactLogAction> ContactLogActions { get; set; }
        public virtual ContactCategory ContactCategory { get; set; }
    }
}
