//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class Country
    {
    	public Country()
        {
            this.AddressEntities = new HashSet<AddressEntity>();
            this.CurrencyTypes = new HashSet<CurrencyType>();
            this.Payments = new HashSet<Payment>();
            this.PaymentTransactions = new HashSet<PaymentTransaction>();
            this.StateProvinces = new HashSet<StateProvince>();
            this.VendorACHes = new HashSet<VendorACH>();
            this.Claims = new HashSet<Claim>();
        }
    
        public int ID { get; set; }
        public string ISOCode { get; set; }
        public string Name { get; set; }
        public string TelephoneCode { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ISOCode3 { get; set; }
    
        public virtual ICollection<AddressEntity> AddressEntities { get; set; }
        public virtual ICollection<CurrencyType> CurrencyTypes { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; }
        public virtual ICollection<StateProvince> StateProvinces { get; set; }
        public virtual ICollection<VendorACH> VendorACHes { get; set; }
        public virtual ICollection<Claim> Claims { get; set; }
    }
}
