//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class CurrencyType
    {
    	public CurrencyType()
        {
            this.Payments = new HashSet<Payment>();
            this.PaymentTransactions = new HashSet<PaymentTransaction>();
            this.ProgramProducts = new HashSet<ProgramProduct>();
            this.ServiceRequests = new HashSet<ServiceRequest>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CurrencySymbol { get; set; }
        public string Abbreviation { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; }
        public virtual ICollection<ProgramProduct> ProgramProducts { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    }
}
