//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class CustomerFeedbackType
    {
    	public CustomerFeedbackType()
        {
            this.CustomerFeedbackDetails = new HashSet<CustomerFeedbackDetail>();
            this.CustomerFeedbackTypeCategories = new HashSet<CustomerFeedbackTypeCategory>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int IsActive { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        public virtual ICollection<CustomerFeedbackDetail> CustomerFeedbackDetails { get; set; }
        public virtual ICollection<CustomerFeedbackTypeCategory> CustomerFeedbackTypeCategories { get; set; }
    }
}
