//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class CustomerFeedback
    {
    	public CustomerFeedback()
        {
            this.CustomerSurveySamples = new HashSet<CustomerSurveySample>();
            this.CustomerFeedbackDetails = new HashSet<CustomerFeedbackDetail>();
            this.CustomerFeedbackGiftCards = new HashSet<CustomerFeedbackGiftCard>();
            this.CustomerFeedbackStatusChangeLogs = new HashSet<CustomerFeedbackStatusChangeLog>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ServiceRequestID { get; set; }
        public Nullable<int> AssignedToUserID { get; set; }
        public Nullable<int> CustomerFeedbackStatusID { get; set; }
        public Nullable<int> CustomerFeedbackPriorityID { get; set; }
        public Nullable<int> CustomerFeedbackSourceID { get; set; }
        public Nullable<int> NextActionID { get; set; }
        public Nullable<int> NextActionAssignedToUserID { get; set; }
        public Nullable<System.DateTime> NextActionScheduleDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string MemberFirstName { get; set; }
        public string MemberLastName { get; set; }
        public string CallRecordingNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string MemberAddressLine1 { get; set; }
        public string MemberAddressLine2 { get; set; }
        public string MemberAddressLine3 { get; set; }
        public string MemberAddressCity { get; set; }
        public string MemberAddressStateProvince { get; set; }
        public Nullable<int> MemberAddressStateProvinceID { get; set; }
        public string MemberAddressPostalCode { get; set; }
        public string MemberAddressCountryCode { get; set; }
        public Nullable<int> MemberAddressCountryID { get; set; }
        public string MemberPhoneNumber { get; set; }
        public string MemberEmail { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string MembershipNumber { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> WorkedByUserID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ResearchComplete { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
    
        public virtual ICollection<CustomerSurveySample> CustomerSurveySamples { get; set; }
        public virtual User User { get; set; }
        public virtual CustomerFeedbackPriority CustomerFeedbackPriority { get; set; }
        public virtual CustomerFeedbackSource CustomerFeedbackSource { get; set; }
        public virtual CustomerFeedbackStatu CustomerFeedbackStatu { get; set; }
        public virtual NextAction NextAction { get; set; }
        public virtual User User1 { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
        public virtual ICollection<CustomerFeedbackDetail> CustomerFeedbackDetails { get; set; }
        public virtual ICollection<CustomerFeedbackGiftCard> CustomerFeedbackGiftCards { get; set; }
        public virtual ICollection<CustomerFeedbackStatusChangeLog> CustomerFeedbackStatusChangeLogs { get; set; }
        public virtual User User2 { get; set; }
    }
}
