//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class CustomerFeedbackSourcePriority
    {
        public int ID { get; set; }
        public int CustomerFeedbackSourceID { get; set; }
        public int CustomerFeedbackPriorityID { get; set; }
    
        public virtual CustomerFeedbackPriority CustomerFeedbackPriority { get; set; }
        public virtual CustomerFeedbackSource CustomerFeedbackSource { get; set; }
    }
}
