//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class EmergencyAssistance
    {
        public int ID { get; set; }
        public Nullable<int> CaseID { get; set; }
        public Nullable<int> InboundCallID { get; set; }
        public string MemberFirstName { get; set; }
        public string MemberLastName { get; set; }
        public Nullable<int> ANIPhoneTypeID { get; set; }
        public string ANIPhoneNumber { get; set; }
        public Nullable<int> ContactPhoneTypeID { get; set; }
        public string ContactPhoneNumber { get; set; }
        public Nullable<int> EmergencyAssistanceReasonID { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoCoordinate { get; set; }
        public string Address { get; set; }
        public string CrossStreet1 { get; set; }
        public string CrossStreet2 { get; set; }
        public string StateProvince { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public string VehicleYear { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleColor { get; set; }
        public string VehicleLicenseNumber { get; set; }
        public string VehicleLicenseState { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string VehicleMakeOther { get; set; }
        public string VehicleModelOther { get; set; }
        public Nullable<int> VehicleLicenseStateCountryID { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual PhoneType PhoneType { get; set; }
        public virtual PhoneType PhoneType1 { get; set; }
        public virtual EmergencyAssistanceReason EmergencyAssistanceReason { get; set; }
        public virtual InboundCall InboundCall { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
