//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class EntityRecordVersionDetail
    {
        public long ID { get; set; }
        public long EntityRecordVersionID { get; set; }
        public int Sequence { get; set; }
        public string SubType { get; set; }
        public Nullable<int> SubTypeSequence { get; set; }
        public string FieldName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
    
        public virtual EntityRecordVersion EntityRecordVersion { get; set; }
    }
}
