//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class Feedback
    {
        public int ID { get; set; }
        public int FeedbackTypeID { get; set; }
        public string Priority { get; set; }
        public string Name { get; set; }
        public Nullable<int> PhoneTypeID { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public string AttachmentFilePath { get; set; }
        public bool IsReviewed { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> PreferedContactMethodID { get; set; }
        public Nullable<int> SourceSystemID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual ContactMethod ContactMethod { get; set; }
        public virtual FeedbackType FeedbackType { get; set; }
        public virtual PhoneType PhoneType { get; set; }
        public virtual SourceSystem SourceSystem { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual Client Client { get; set; }
    }
}
