//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceRequest
    {
        public int RecID { get; set; }
        public Nullable<int> ETL_Load_ID { get; set; }
        public Nullable<bool> ProcessFlag { get; set; }
        public string Status { get; set; }
        public string ErrorDescription { get; set; }
        public Nullable<System.DateTime> AddDateTime { get; set; }
        public Nullable<decimal> Division { get; set; }
        public string CustomerNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> InvoiceDueDate { get; set; }
        public Nullable<decimal> TermsCode { get; set; }
        public string CustomerPONumber { get; set; }
        public string Comment { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> LineAmount { get; set; }
        public string AdditionalComment { get; set; }
        public string AccountingSystemAddressCode { get; set; }
        public string POPrefix { get; set; }
        public Nullable<System.DateTime> BillingPeriodEndDate { get; set; }
        public string InvoiceDescription { get; set; }
        public Nullable<decimal> LineQuantity { get; set; }
        public Nullable<decimal> LineCost { get; set; }
        public Nullable<decimal> LineNumber { get; set; }
    }
}
