//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class Mobile_CallForService
    {
    	public Mobile_CallForService()
        {
            this.InboundCalls = new HashSet<InboundCall>();
        }
    
        public int PKID { get; set; }
        public string MemberNumber { get; set; }
        public string GUID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MemberDevicePhoneNumber { get; set; }
        public string locationLatitude { get; set; }
        public string locationLongtitude { get; set; }
        public string serviceType { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string memberDeviceGUID { get; set; }
        public string appOrgName { get; set; }
    
        public virtual ICollection<InboundCall> InboundCalls { get; set; }
    }
}
