//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class MotorcycleType
    {
    	public MotorcycleType()
        {
            this.MotorcycleMakeModels = new HashSet<MotorcycleMakeModel>();
            this.MakeModels = new HashSet<MakeModel>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageFile { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<MotorcycleMakeModel> MotorcycleMakeModels { get; set; }
        public virtual ICollection<MakeModel> MakeModels { get; set; }
    }
}
