//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class NextAction
    {
    	public NextAction()
        {
            this.Claims = new HashSet<Claim>();
            this.NextActionRoles = new HashSet<NextActionRole>();
            this.NextActionEntities = new HashSet<NextActionEntity>();
            this.ServiceRequests = new HashSet<ServiceRequest>();
            this.CustomerFeedbacks = new HashSet<CustomerFeedback>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ContactCategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> DefaultPriorityID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> DefaultScheduleDateInterval { get; set; }
        public string DefaultScheduleDateIntervalUOM { get; set; }
        public Nullable<int> DefaultAssignedToUserID { get; set; }
        public Nullable<bool> IsShowConfirmPrompt { get; set; }
    
        public virtual ICollection<Claim> Claims { get; set; }
        public virtual ContactCategory ContactCategory { get; set; }
        public virtual ServiceRequestPriority ServiceRequestPriority { get; set; }
        public virtual ICollection<NextActionRole> NextActionRoles { get; set; }
        public virtual ICollection<NextActionEntity> NextActionEntities { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CustomerFeedback> CustomerFeedbacks { get; set; }
    }
}
