//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class OrganizationClient
    {
        public int ID { get; set; }
        public int OrganizationID { get; set; }
        public int ClientID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
