//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class OrganizationRole
    {
        public int ID { get; set; }
        public int OrganizationID { get; set; }
        public System.Guid RoleID { get; set; }
    
        public virtual aspnet_Roles aspnet_Roles { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
