//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class PaymentType
    {
    	public PaymentType()
        {
            this.BillToPaymentTypes = new HashSet<BillToPaymentType>();
            this.Claims = new HashSet<Claim>();
            this.Payments = new HashSet<Payment>();
            this.PaymentTransactions = new HashSet<PaymentTransaction>();
            this.VendorApplicationPaymentTypes = new HashSet<VendorApplicationPaymentType>();
            this.VendorInvoices = new HashSet<VendorInvoice>();
            this.VendorLocationPaymentTypes = new HashSet<VendorLocationPaymentType>();
            this.ServiceRequests = new HashSet<ServiceRequest>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.MemberPaymentMethods = new HashSet<MemberPaymentMethod>();
            this.PaymentTypeEntities = new HashSet<PaymentTypeEntity>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PaymentCategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsShownOnVendor { get; set; }
    
        public virtual ICollection<BillToPaymentType> BillToPaymentTypes { get; set; }
        public virtual ICollection<Claim> Claims { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual PaymentCategory PaymentCategory { get; set; }
        public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; }
        public virtual ICollection<VendorApplicationPaymentType> VendorApplicationPaymentTypes { get; set; }
        public virtual ICollection<VendorInvoice> VendorInvoices { get; set; }
        public virtual ICollection<VendorLocationPaymentType> VendorLocationPaymentTypes { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<MemberPaymentMethod> MemberPaymentMethods { get; set; }
        public virtual ICollection<PaymentTypeEntity> PaymentTypeEntities { get; set; }
    }
}
