//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class Person
    {
    	public Person()
        {
            this.PersonNotificationTimings = new HashSet<PersonNotificationTiming>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EntityID { get; set; }
        public Nullable<int> RecordID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public bool IsNotificationEnabled { get; set; }
        public bool IsDoNotDisturbEnabled { get; set; }
        public Nullable<System.TimeSpan> DoNotDisturbStartTime { get; set; }
        public Nullable<System.TimeSpan> DoNotDisturbEndTime { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual TimeZone TimeZone { get; set; }
        public virtual ICollection<PersonNotificationTiming> PersonNotificationTimings { get; set; }
    }
}
