//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class PhoneEntity
    {
        public int ID { get; set; }
        public int EntityID { get; set; }
        public int RecordID { get; set; }
        public Nullable<int> PhoneTypeID { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> IndexPhoneNumber { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> CreateBatchID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> ModifyBatchID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual PhoneType PhoneType { get; set; }
    }
}
