//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class PortletSection
    {
    	public PortletSection()
        {
            this.PortletColumns = new HashSet<PortletColumn>();
            this.UserPortlets = new HashSet<UserPortlet>();
            this.UserPortletDefaultByRoles = new HashSet<UserPortletDefaultByRole>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool AllowDragDrop { get; set; }
    
        public virtual ICollection<PortletColumn> PortletColumns { get; set; }
        public virtual ICollection<UserPortlet> UserPortlets { get; set; }
        public virtual ICollection<UserPortletDefaultByRole> UserPortletDefaultByRoles { get; set; }
    }
}
