//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class PostLoginPrompt
    {
    	public PostLoginPrompt()
        {
            this.VendorUsers = new HashSet<VendorUser>();
            this.ClientUsers = new HashSet<ClientUser>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PageReference { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual ICollection<VendorUser> VendorUsers { get; set; }
        public virtual ICollection<ClientUser> ClientUsers { get; set; }
    }
}
