//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    
    [Serializable] 
    public partial class PreviousCallList
    {
        public Nullable<int> ContactSourceID { get; set; }
        public string ContactSourceName { get; set; }
        public int ContactLogID { get; set; }
        public string Company { get; set; }
        public string TalkedTo { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string ContactActionName { get; set; }
    }
}
