//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class Product
    {
    	public Product()
        {
            this.ContractRateScheduleProducts = new HashSet<ContractRateScheduleProduct>();
            this.ContractRateScheduleProductLogs = new HashSet<ContractRateScheduleProductLog>();
            this.MarketLocationProductRates = new HashSet<MarketLocationProductRate>();
            this.MemberProducts = new HashSet<MemberProduct>();
            this.ProductRateTypes = new HashSet<ProductRateType>();
            this.ProgramProducts = new HashSet<ProgramProduct>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.ProductCategoryQuestionValues = new HashSet<ProductCategoryQuestionValue>();
            this.VendorApplicationProducts = new HashSet<VendorApplicationProduct>();
            this.VendorLocationProducts = new HashSet<VendorLocationProduct>();
            this.VendorProducts = new HashSet<VendorProduct>();
            this.ServiceRequests = new HashSet<ServiceRequest>();
            this.ServiceRequests1 = new HashSet<ServiceRequest>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.BillingDefinitionInvoiceLines = new HashSet<BillingDefinitionInvoiceLine>();
            this.BillingInvoiceLines = new HashSet<BillingInvoiceLine>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> ProductSubTypeID { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public Nullable<int> VehicleCategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sequence { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<bool> IsShowOnPO { get; set; }
        public string AccountingSystemGLCode { get; set; }
        public string AccountingSystemItemCode { get; set; }
        public Nullable<bool> ShowOnVendorPortal { get; set; }
        public Nullable<bool> ShowOnVendorMaintenance { get; set; }
    
        public virtual ICollection<ContractRateScheduleProduct> ContractRateScheduleProducts { get; set; }
        public virtual ICollection<ContractRateScheduleProductLog> ContractRateScheduleProductLogs { get; set; }
        public virtual ICollection<MarketLocationProductRate> MarketLocationProductRates { get; set; }
        public virtual ICollection<MemberProduct> MemberProducts { get; set; }
        public virtual ICollection<ProductRateType> ProductRateTypes { get; set; }
        public virtual ICollection<ProgramProduct> ProgramProducts { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductSubType ProductSubType { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual VehicleCategory VehicleCategory { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual ICollection<ProductCategoryQuestionValue> ProductCategoryQuestionValues { get; set; }
        public virtual ICollection<VendorApplicationProduct> VendorApplicationProducts { get; set; }
        public virtual ICollection<VendorLocationProduct> VendorLocationProducts { get; set; }
        public virtual ICollection<VendorProduct> VendorProducts { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests1 { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<BillingDefinitionInvoiceLine> BillingDefinitionInvoiceLines { get; set; }
        public virtual ICollection<BillingInvoiceLine> BillingInvoiceLines { get; set; }
    }
}
