//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class ProductCategoryQuestionProgram
    {
        public int ID { get; set; }
        public int ProgramID { get; set; }
        public int ProductCategoryQuestionID { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public Nullable<int> VehicleCategoryID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ProductCategoryQuestion ProductCategoryQuestion { get; set; }
        public virtual VehicleCategory VehicleCategory { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual Program Program { get; set; }
    }
}
