//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class ProductCategoryQuestionLink
    {
        public int ID { get; set; }
        public int ProductCategoryQuestionID { get; set; }
        public int ParentProductCategoryQuestionID { get; set; }
        public Nullable<int> ProductCategoryQuestionValueID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ProductCategoryQuestion ProductCategoryQuestion { get; set; }
        public virtual ProductCategoryQuestion ProductCategoryQuestion1 { get; set; }
        public virtual ProductCategoryQuestionValue ProductCategoryQuestionValue { get; set; }
    }
}
