//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class ProductCategory
    {
    	public ProductCategory()
        {
            this.Claims = new HashSet<Claim>();
            this.ProductCategoryQuestions = new HashSet<ProductCategoryQuestion>();
            this.ProgramProductCategories = new HashSet<ProgramProductCategory>();
            this.Products = new HashSet<Product>();
            this.ServiceRequests = new HashSet<ServiceRequest>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsVehicleRequired { get; set; }
        public Nullable<bool> IsShownOnScreen { get; set; }
    
        public virtual ICollection<Claim> Claims { get; set; }
        public virtual ICollection<ProductCategoryQuestion> ProductCategoryQuestions { get; set; }
        public virtual ICollection<ProgramProductCategory> ProgramProductCategories { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
    }
}
