//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class ProgramProduct
    {
        public int ID { get; set; }
        public int ProgramID { get; set; }
        public int ProductID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> ServiceCoverageLimit { get; set; }
        public Nullable<bool> IsServiceCoverageBestValue { get; set; }
        public Nullable<decimal> MaterialsCoverageLimit { get; set; }
        public Nullable<bool> IsMaterialsMemberPay { get; set; }
        public Nullable<int> ServiceMileageLimit { get; set; }
        public Nullable<bool> IsServiceMileageUnlimited { get; set; }
        public Nullable<bool> IsServiceMileageOverageAllowed { get; set; }
        public Nullable<bool> IsReimbursementOnly { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<bool> IsServiceGuaranteed { get; set; }
        public string ServiceCoverageDescription { get; set; }
        public Nullable<int> CurrencyTypeID { get; set; }
        public string ServiceMileageLimitUOM { get; set; }
    
        public virtual CurrencyType CurrencyType { get; set; }
        public virtual Program Program { get; set; }
        public virtual Product Product { get; set; }
    }
}
