//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class Program
    {
    	public Program()
        {
            this.Cases = new HashSet<Case>();
            this.Claims = new HashSet<Claim>();
            this.ClientChangeLogMappings = new HashSet<ClientChangeLogMapping>();
            this.DataGroupPrograms = new HashSet<DataGroupProgram>();
            this.HagertyProgramMaps = new HashSet<HagertyProgramMap>();
            this.InboundCalls = new HashSet<InboundCall>();
            this.MemberSearchProgramGroupings = new HashSet<MemberSearchProgramGrouping>();
            this.PhoneSystemConfigurations = new HashSet<PhoneSystemConfiguration>();
            this.ProductCategoryQuestionPrograms = new HashSet<ProductCategoryQuestionProgram>();
            this.Program1 = new HashSet<Program>();
            this.ProgramConfigurations = new HashSet<ProgramConfiguration>();
            this.ProgramDataItems = new HashSet<ProgramDataItem>();
            this.ProgramProductCategories = new HashSet<ProgramProductCategory>();
            this.ProgramProducts = new HashSet<ProgramProduct>();
            this.ProgramVehicleTypes = new HashSet<ProgramVehicleType>();
            this.MemberProgramChangeMappings = new HashSet<MemberProgramChangeMapping>();
            this.MemberProgramChangeMappings1 = new HashSet<MemberProgramChangeMapping>();
            this.Members = new HashSet<Member>();
            this.BillingDefinitionInvoiceLineEventPrograms = new HashSet<BillingDefinitionInvoiceLineEventProgram>();
            this.BillingInvoiceDetails = new HashSet<BillingInvoiceDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentProgramID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsServiceGuaranteed { get; set; }
        public Nullable<decimal> CallFee { get; set; }
        public Nullable<decimal> DispatchFee { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsAudited { get; set; }
        public string LegacyType { get; set; }
        public string LegacyCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<bool> IsClosedLoopAutomated { get; set; }
        public bool IsGroup { get; set; }
        public Nullable<bool> IsWebRegistrationEnabled { get; set; }
    
        public virtual ICollection<Case> Cases { get; set; }
        public virtual ICollection<Claim> Claims { get; set; }
        public virtual Client Client { get; set; }
        public virtual ICollection<ClientChangeLogMapping> ClientChangeLogMappings { get; set; }
        public virtual ICollection<DataGroupProgram> DataGroupPrograms { get; set; }
        public virtual ICollection<HagertyProgramMap> HagertyProgramMaps { get; set; }
        public virtual ICollection<InboundCall> InboundCalls { get; set; }
        public virtual ICollection<MemberSearchProgramGrouping> MemberSearchProgramGroupings { get; set; }
        public virtual ICollection<PhoneSystemConfiguration> PhoneSystemConfigurations { get; set; }
        public virtual ICollection<ProductCategoryQuestionProgram> ProductCategoryQuestionPrograms { get; set; }
        public virtual ICollection<Program> Program1 { get; set; }
        public virtual Program Program2 { get; set; }
        public virtual ICollection<ProgramConfiguration> ProgramConfigurations { get; set; }
        public virtual ICollection<ProgramDataItem> ProgramDataItems { get; set; }
        public virtual ICollection<ProgramProductCategory> ProgramProductCategories { get; set; }
        public virtual ICollection<ProgramProduct> ProgramProducts { get; set; }
        public virtual ICollection<ProgramVehicleType> ProgramVehicleTypes { get; set; }
        public virtual ICollection<MemberProgramChangeMapping> MemberProgramChangeMappings { get; set; }
        public virtual ICollection<MemberProgramChangeMapping> MemberProgramChangeMappings1 { get; set; }
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<BillingDefinitionInvoiceLineEventProgram> BillingDefinitionInvoiceLineEventPrograms { get; set; }
        public virtual ICollection<BillingInvoiceDetail> BillingInvoiceDetails { get; set; }
    }
}
