//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class PurchaseOrderDetail
    {
        public int ID { get; set; }
        public int PurchaseOrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductRateID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<decimal> ContractedRate { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> ExtendedAmount { get; set; }
        public Nullable<bool> IsTaxable { get; set; }
        public Nullable<bool> IsMemberPay { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
