//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class QueueStatu
    {
        public int ID { get; set; }
        public Nullable<int> Minutes { get; set; }
        public string Color { get; set; }
        public string SRStatusName { get; set; }
        public string Action { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
