//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class Securable
    {
    	public Securable()
        {
            this.AccessControlLists = new HashSet<AccessControlList>();
            this.Securable1 = new HashSet<Securable>();
            this.Portlets = new HashSet<Portlet>();
            this.Reports = new HashSet<Report>();
        }
    
        public int ID { get; set; }
        public string FriendlyName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string SecurityContext { get; set; }
    
        public virtual ICollection<AccessControlList> AccessControlLists { get; set; }
        public virtual ICollection<Securable> Securable1 { get; set; }
        public virtual Securable Securable2 { get; set; }
        public virtual ICollection<Portlet> Portlets { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
    }
}
