//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class ServiceRequestException
    {
        public int ID { get; set; }
        public int ServiceRequestID { get; set; }
        public string RequestArea { get; set; }
        public string ExceptionMessage { get; set; }
    
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
