//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class TemplateTag
    {
    	public TemplateTag()
        {
            this.EventCategoryTemplateTags = new HashSet<EventCategoryTemplateTag>();
        }
    
        public int ID { get; set; }
        public string Tag { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<EventCategoryTemplateTag> EventCategoryTemplateTags { get; set; }
    }
}
