//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class TemporaryCreditCard_Import
    {
        public long RecordID { get; set; }
        public System.Guid ProcessIdentifier { get; set; }
        public string PurchaseID_CreditCardIssueNumber { get; set; }
        public string CPN_PAN_CreditCardNumber { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public Nullable<int> VendorInvoiceID { get; set; }
        public System.DateTime CREATE_DATE_IssueDate_TransactionDate { get; set; }
        public string USER_NAME_IssueBy_TransactionBy { get; set; }
        public string IssueStatus { get; set; }
        public string CDF_PO_ReferencePurchaseOrderNumber { get; set; }
        public string CDF_PO_OriginalReferencePurchaseOrderNumber { get; set; }
        public string CDF_ISP_Vendor_ReferenceVendorNumber { get; set; }
        public decimal ApprovedAmount { get; set; }
        public decimal TotalChargeAmount { get; set; }
        public int TemporaryCreditCardStatusID { get; set; }
        public string ExceptionMessage { get; set; }
        public string Note { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public int HISTORY_ID_TransactionSequence { get; set; }
        public string ACTION_TYPE_TransactionType { get; set; }
        public decimal REQUESTED_AMOUNT_RequestedAmount { get; set; }
        public decimal APPROVED_AMOUNT_ApprovedAmount { get; set; }
        public decimal AVAILABLE_BALANCE_AvailableBalance { get; set; }
        public Nullable<System.DateTime> ChargeDate { get; set; }
        public Nullable<decimal> ChargeAmount { get; set; }
        public string ChargeDescription { get; set; }
        public Nullable<int> TemporaryCreditCardID { get; set; }
        public Nullable<int> TemporaryCreditCardDetailsID { get; set; }
        public string PURCHASE_TYPE { get; set; }
    }
}
