//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class UserDataGroup
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int DataGroupID { get; set; }
    
        public virtual DataGroup DataGroup { get; set; }
        public virtual User User { get; set; }
    }
}
