//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class UserPasswordHistory
    {
        public int ID { get; set; }
        public Nullable<System.Guid> aspnet_UserId { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> InitialUseDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<int> PasswordFormat { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
