//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class UserPortletDefaultByRole
    {
        public int ID { get; set; }
        public Nullable<System.Guid> RoleID { get; set; }
        public Nullable<int> PortletSectionID { get; set; }
        public Nullable<int> PortletID { get; set; }
        public Nullable<int> ColumnPosition { get; set; }
        public Nullable<int> RowPosition { get; set; }
        public Nullable<bool> IsDisplayedByDefault { get; set; }
    
        public virtual aspnet_Roles aspnet_Roles { get; set; }
        public virtual Portlet Portlet { get; set; }
        public virtual PortletSection PortletSection { get; set; }
    }
}
