//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class User
    {
    	public User()
        {
            this.Cases = new HashSet<Case>();
            this.InboundCalls = new HashSet<InboundCall>();
            this.NextActions = new HashSet<NextAction>();
            this.ServiceRequests = new HashSet<ServiceRequest>();
            this.User1 = new HashSet<User>();
            this.UserDataGroups = new HashSet<UserDataGroup>();
            this.CustomerFeedbacks = new HashSet<CustomerFeedback>();
            this.CustomerFeedbacks1 = new HashSet<CustomerFeedback>();
            this.CustomerFeedbacks2 = new HashSet<CustomerFeedback>();
        }
    
        public int ID { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public System.Guid aspnet_UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AgentNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string PhoneUserID { get; set; }
        public string PhonePassword { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<int> Pin { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<Case> Cases { get; set; }
        public virtual ICollection<InboundCall> InboundCalls { get; set; }
        public virtual ICollection<NextAction> NextActions { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<UserDataGroup> UserDataGroups { get; set; }
        public virtual ICollection<CustomerFeedback> CustomerFeedbacks { get; set; }
        public virtual ICollection<CustomerFeedback> CustomerFeedbacks1 { get; set; }
        public virtual ICollection<CustomerFeedback> CustomerFeedbacks2 { get; set; }
    }
}
