//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class VehicleType
    {
    	public VehicleType()
        {
            this.Cases = new HashSet<Case>();
            this.Claims = new HashSet<Claim>();
            this.EmergencyAssistances = new HashSet<EmergencyAssistance>();
            this.ProductCategoryQuestionPrograms = new HashSet<ProductCategoryQuestionProgram>();
            this.ProductCategoryQuestionVehicleTypes = new HashSet<ProductCategoryQuestionVehicleType>();
            this.ProgramProductCategories = new HashSet<ProgramProductCategory>();
            this.ProgramVehicleTypes = new HashSet<ProgramVehicleType>();
            this.Vehicles = new HashSet<Vehicle>();
            this.VehicleTypeBusinessSearchOptions = new HashSet<VehicleTypeBusinessSearchOption>();
            this.VehicleTypeVehicleCategories = new HashSet<VehicleTypeVehicleCategory>();
            this.VehicleTypeVehicleDiagnosticCodes = new HashSet<VehicleTypeVehicleDiagnosticCode>();
            this.Products = new HashSet<Product>();
            this.MakeModels = new HashSet<MakeModel>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Case> Cases { get; set; }
        public virtual ICollection<Claim> Claims { get; set; }
        public virtual ICollection<EmergencyAssistance> EmergencyAssistances { get; set; }
        public virtual ICollection<ProductCategoryQuestionProgram> ProductCategoryQuestionPrograms { get; set; }
        public virtual ICollection<ProductCategoryQuestionVehicleType> ProductCategoryQuestionVehicleTypes { get; set; }
        public virtual ICollection<ProgramProductCategory> ProgramProductCategories { get; set; }
        public virtual ICollection<ProgramVehicleType> ProgramVehicleTypes { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual ICollection<VehicleTypeBusinessSearchOption> VehicleTypeBusinessSearchOptions { get; set; }
        public virtual ICollection<VehicleTypeVehicleCategory> VehicleTypeVehicleCategories { get; set; }
        public virtual ICollection<VehicleTypeVehicleDiagnosticCode> VehicleTypeVehicleDiagnosticCodes { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<MakeModel> MakeModels { get; set; }
    }
}
