//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class Vehicle
    {
    	public Vehicle()
        {
            this.Cases = new HashSet<Case>();
            this.Claims = new HashSet<Claim>();
        }
    
        public int ID { get; set; }
        public Nullable<int> VehicleCategoryID { get; set; }
        public Nullable<int> RVTypeID { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public Nullable<int> MembershipID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string VIN { get; set; }
        public string Year { get; set; }
        public string Make { get; set; }
        public string MakeOther { get; set; }
        public string Model { get; set; }
        public string ModelOther { get; set; }
        public string LicenseNumber { get; set; }
        public string LicenseState { get; set; }
        public string Description { get; set; }
        public string Color { get; set; }
        public Nullable<int> Length { get; set; }
        public string Height { get; set; }
        public string TireSize { get; set; }
        public string TireBrand { get; set; }
        public string TireBrandOther { get; set; }
        public Nullable<int> TrailerTypeID { get; set; }
        public string TrailerTypeOther { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> NumberofAxles { get; set; }
        public Nullable<int> HitchTypeID { get; set; }
        public string HitchTypeOther { get; set; }
        public string TrailerBallSize { get; set; }
        public string TrailerBallSizeOther { get; set; }
        public string Transmission { get; set; }
        public string Engine { get; set; }
        public Nullable<int> GVWR { get; set; }
        public string Chassis { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> WarrantyStartDate { get; set; }
        public Nullable<int> StartMileage { get; set; }
        public Nullable<int> EndMileage { get; set; }
        public string MileageUOM { get; set; }
        public Nullable<bool> IsFirstOwner { get; set; }
        public Nullable<bool> IsSportUtilityRV { get; set; }
        public string Source { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreateBatchID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> ModifyBatchID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> VehicleLicenseCountryID { get; set; }
        public Nullable<int> WarrantyPeriod { get; set; }
        public string WarrantyPeriodUOM { get; set; }
        public Nullable<int> WarrantyMileage { get; set; }
        public Nullable<System.DateTime> WarrantyEndDate { get; set; }
    
        public virtual ICollection<Case> Cases { get; set; }
        public virtual HitchType HitchType { get; set; }
        public virtual Membership Membership { get; set; }
        public virtual RVType RVType { get; set; }
        public virtual TrailerType TrailerType { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual VehicleCategory VehicleCategory { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<Claim> Claims { get; set; }
    }
}
