//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class VehicleDiagnosticCode
    {
    	public VehicleDiagnosticCode()
        {
            this.ClaimVehicleDiagnosticCodes = new HashSet<ClaimVehicleDiagnosticCode>();
            this.ServiceRequestVehicleDiagnosticCodes = new HashSet<ServiceRequestVehicleDiagnosticCode>();
            this.VehicleTypeVehicleDiagnosticCodes = new HashSet<VehicleTypeVehicleDiagnosticCode>();
        }
    
        public int ID { get; set; }
        public Nullable<int> VehicleDiagnosticCategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string LegacyCode { get; set; }
        public string FordStandardCode { get; set; }
        public string FordWarrantyCode { get; set; }
        public string FordAfterWarrantyCode { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FordClaimCode { get; set; }
    
        public virtual ICollection<ClaimVehicleDiagnosticCode> ClaimVehicleDiagnosticCodes { get; set; }
        public virtual ICollection<ServiceRequestVehicleDiagnosticCode> ServiceRequestVehicleDiagnosticCodes { get; set; }
        public virtual VehicleDiagnosticCategory VehicleDiagnosticCategory { get; set; }
        public virtual ICollection<VehicleTypeVehicleDiagnosticCode> VehicleTypeVehicleDiagnosticCodes { get; set; }
    }
}
