//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class Vendor
    {
    	public Vendor()
        {
            this.Claims = new HashSet<Claim>();
            this.Feedbacks = new HashSet<Feedback>();
            this.MembershipBlackListVendors = new HashSet<MembershipBlackListVendor>();
            this.VendorLocations = new HashSet<VendorLocation>();
            this.VendorACHes = new HashSet<VendorACH>();
            this.VendorInvoices = new HashSet<VendorInvoice>();
            this.VendorProducts = new HashSet<VendorProduct>();
            this.VendorStatusLogs = new HashSet<VendorStatusLog>();
            this.VendorUsers = new HashSet<VendorUser>();
            this.Contracts = new HashSet<Contract>();
            this.VendorApplications = new HashSet<VendorApplication>();
            this.AccessControlLists = new HashSet<AccessControlList>();
            this.Members = new HashSet<Member>();
        }
    
        public int ID { get; set; }
        public string VendorNumber { get; set; }
        public string Name { get; set; }
        public Nullable<int> AdministrativeRating { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> InsuranceExpirationDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> VendorStatusID { get; set; }
        public string CorporationName { get; set; }
        public string InsuranceCarrierName { get; set; }
        public string InsurancePolicyNumber { get; set; }
        public Nullable<bool> IsInsuranceCertificateOnFile { get; set; }
        public Nullable<bool> IsW9OnFile { get; set; }
        public Nullable<bool> IsEmployeeBackgroundChecked { get; set; }
        public string IsEmployeeBackgroundCheckedComment { get; set; }
        public Nullable<bool> IsEmployeeDrugTested { get; set; }
        public string IsEmployeeDrugTestedComment { get; set; }
        public Nullable<bool> IsDriverUniformed { get; set; }
        public string IsDriverUniformedComment { get; set; }
        public Nullable<bool> IsEachServiceTruckMarked { get; set; }
        public string IsEachServiceTruckMarkedComment { get; set; }
        public string DepartmentOfTransportationNumber { get; set; }
        public string MotorCarrierNumber { get; set; }
        public Nullable<System.DateTime> AdministrativeRatingModifyDate { get; set; }
        public Nullable<int> SourceSystemID { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string TaxEIN { get; set; }
        public string TaxSSN { get; set; }
        public string W9SignedBy { get; set; }
        public string TaxClassification { get; set; }
        public string TaxClassificationOther { get; set; }
        public Nullable<bool> IsLevyActive { get; set; }
        public string LevyRecipientName { get; set; }
        public Nullable<bool> IsPaymentOnHold { get; set; }
        public Nullable<int> VendorRegionID { get; set; }
        public Nullable<bool> IsVirtualLocationEnabled { get; set; }
        public Nullable<bool> IsInsuranceAdditional { get; set; }
        public string ClientVendorKey { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> DispatchSoftwareProductID { get; set; }
        public string DispatchSoftwareProductOther { get; set; }
        public Nullable<int> DriverSoftwareProductID { get; set; }
        public Nullable<int> DispatchGPSNetworkID { get; set; }
        public string DriverSoftwareProductOther { get; set; }
        public string DispatchGPSNetworkOther { get; set; }
    
        public virtual ICollection<Claim> Claims { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<MembershipBlackListVendor> MembershipBlackListVendors { get; set; }
        public virtual SourceSystem SourceSystem { get; set; }
        public virtual ICollection<VendorLocation> VendorLocations { get; set; }
        public virtual VendorRegion VendorRegion { get; set; }
        public virtual VendorStatu VendorStatu { get; set; }
        public virtual ICollection<VendorACH> VendorACHes { get; set; }
        public virtual ICollection<VendorInvoice> VendorInvoices { get; set; }
        public virtual ICollection<VendorProduct> VendorProducts { get; set; }
        public virtual ICollection<VendorStatusLog> VendorStatusLogs { get; set; }
        public virtual ICollection<VendorUser> VendorUsers { get; set; }
        public virtual Client Client { get; set; }
        public virtual DispatchGPSNetwork DispatchGPSNetwork { get; set; }
        public virtual DispatchSoftwareProduct DispatchSoftwareProduct { get; set; }
        public virtual DispatchSoftwareProduct DispatchSoftwareProduct1 { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<VendorApplication> VendorApplications { get; set; }
        public virtual ICollection<AccessControlList> AccessControlLists { get; set; }
        public virtual ICollection<Member> Members { get; set; }
    }
}
