//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class VendorApplicationPostalCode
    {
        public int ID { get; set; }
        public Nullable<int> VendorApplicationID { get; set; }
        public string PostalCode { get; set; }
        public Nullable<bool> IsSecondary { get; set; }
    
        public virtual VendorApplication VendorApplication { get; set; }
    }
}
