//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class VendorInvoice
    {
    	public VendorInvoice()
        {
            this.VendorInvoiceExceptions = new HashSet<VendorInvoiceException>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> VendorInvoiceStatusID { get; set; }
        public Nullable<int> SourceSystemID { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<int> ReceiveContactMethodID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public string BillingBusinessName { get; set; }
        public string BillingContactName { get; set; }
        public string BillingAddressLine1 { get; set; }
        public string BillingAddressLine2 { get; set; }
        public string BillingAddressLine3 { get; set; }
        public string BillingAddressCity { get; set; }
        public string BillingAddressStateProvince { get; set; }
        public string BillingAddressPostalCode { get; set; }
        public string BillingAddressCountryCode { get; set; }
        public Nullable<System.DateTime> ToBePaidDate { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public Nullable<int> ExportBatchID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string PaymentNumber { get; set; }
        public Nullable<System.DateTime> CheckClearedDate { get; set; }
        public Nullable<int> ActualETAMinutes { get; set; }
        public string Last8OfVIN { get; set; }
        public Nullable<int> VehicleMileage { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> AccountingInvoiceBatchID { get; set; }
        public Nullable<int> VendorInvoicePaymentDifferenceReasonCodeID { get; set; }
        public string GLExpenseAccount { get; set; }
    
        public virtual ContactMethod ContactMethod { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual SourceSystem SourceSystem { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual VendorInvoicePaymentDifferenceReasonCode VendorInvoicePaymentDifferenceReasonCode { get; set; }
        public virtual VendorInvoiceStatu VendorInvoiceStatu { get; set; }
        public virtual ICollection<VendorInvoiceException> VendorInvoiceExceptions { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
