//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class VendorUser
    {
        public int ID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public System.Guid aspnet_UserID { get; set; }
        public Nullable<int> PostLoginPromptID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> IsHelpOverlayEnabled { get; set; }
        public Nullable<bool> ChangePassword { get; set; }
        public Nullable<bool> ReceiveNotification { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string PasswordResetToken { get; set; }
        public Nullable<System.DateTime> PasswordTokenGeneratedOn { get; set; }
        public Nullable<int> PasswordTokenValidityInHours { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual PostLoginPrompt PostLoginPrompt { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
