//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] 
    public partial class VendorRegion
    {
    	public VendorRegion()
        {
            this.Vendors = new HashSet<Vendor>();
            this.VendorRegionStateProvinces = new HashSet<VendorRegionStateProvince>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual ICollection<Vendor> Vendors { get; set; }
        public virtual ICollection<VendorRegionStateProvince> VendorRegionStateProvinces { get; set; }
    }
}
