//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martex.DMS.BLL.DigitalDispatchAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.towbook.com/receivers/pinnacle/", ConfigurationName="DigitalDispatchAPI.TowbookServiceSoap")]
    public interface TowbookServiceSoap {
        
        // CODEGEN: Generating message contract since element name apiKey from namespace https://api.towbook.com/receivers/pinnacle/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://api.towbook.com/receivers/pinnacle/DDXMLReceiveMessageEx", ReplyAction="*")]
        Martex.DMS.BLL.DigitalDispatchAPI.DDXMLReceiveMessageExResponse DDXMLReceiveMessageEx(Martex.DMS.BLL.DigitalDispatchAPI.DDXMLReceiveMessageExRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DDXMLReceiveMessageExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DDXMLReceiveMessageEx", Namespace="https://api.towbook.com/receivers/pinnacle/", Order=0)]
        public Martex.DMS.BLL.DigitalDispatchAPI.DDXMLReceiveMessageExRequestBody Body;
        
        public DDXMLReceiveMessageExRequest() {
        }
        
        public DDXMLReceiveMessageExRequest(Martex.DMS.BLL.DigitalDispatchAPI.DDXMLReceiveMessageExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://api.towbook.com/receivers/pinnacle/")]
    public partial class DDXMLReceiveMessageExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlMessage;
        
        public DDXMLReceiveMessageExRequestBody() {
        }
        
        public DDXMLReceiveMessageExRequestBody(string apiKey, string xmlMessage) {
            this.apiKey = apiKey;
            this.xmlMessage = xmlMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DDXMLReceiveMessageExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DDXMLReceiveMessageExResponse", Namespace="https://api.towbook.com/receivers/pinnacle/", Order=0)]
        public Martex.DMS.BLL.DigitalDispatchAPI.DDXMLReceiveMessageExResponseBody Body;
        
        public DDXMLReceiveMessageExResponse() {
        }
        
        public DDXMLReceiveMessageExResponse(Martex.DMS.BLL.DigitalDispatchAPI.DDXMLReceiveMessageExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://api.towbook.com/receivers/pinnacle/")]
    public partial class DDXMLReceiveMessageExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DDXMLReceiveMessageExResult;
        
        public DDXMLReceiveMessageExResponseBody() {
        }
        
        public DDXMLReceiveMessageExResponseBody(string DDXMLReceiveMessageExResult) {
            this.DDXMLReceiveMessageExResult = DDXMLReceiveMessageExResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TowbookServiceSoapChannel : Martex.DMS.BLL.DigitalDispatchAPI.TowbookServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TowbookServiceSoapClient : System.ServiceModel.ClientBase<Martex.DMS.BLL.DigitalDispatchAPI.TowbookServiceSoap>, Martex.DMS.BLL.DigitalDispatchAPI.TowbookServiceSoap {
        
        public TowbookServiceSoapClient() {
        }
        
        public TowbookServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TowbookServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TowbookServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TowbookServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Martex.DMS.BLL.DigitalDispatchAPI.DDXMLReceiveMessageExResponse Martex.DMS.BLL.DigitalDispatchAPI.TowbookServiceSoap.DDXMLReceiveMessageEx(Martex.DMS.BLL.DigitalDispatchAPI.DDXMLReceiveMessageExRequest request) {
            return base.Channel.DDXMLReceiveMessageEx(request);
        }
        
        public string DDXMLReceiveMessageEx(string apiKey, string xmlMessage) {
            Martex.DMS.BLL.DigitalDispatchAPI.DDXMLReceiveMessageExRequest inValue = new Martex.DMS.BLL.DigitalDispatchAPI.DDXMLReceiveMessageExRequest();
            inValue.Body = new Martex.DMS.BLL.DigitalDispatchAPI.DDXMLReceiveMessageExRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.xmlMessage = xmlMessage;
            Martex.DMS.BLL.DigitalDispatchAPI.DDXMLReceiveMessageExResponse retVal = ((Martex.DMS.BLL.DigitalDispatchAPI.TowbookServiceSoap)(this)).DDXMLReceiveMessageEx(inValue);
            return retVal.Body.DDXMLReceiveMessageExResult;
        }
    }
}
